### PR TITLE
[SYCL] Add support for NVPTX device printf

### LINKED ISSUE #1154: [CUDA] printfs results in ptxas error: Call has wrong number of parameters
Testing the latest iteration of #1091 (as of 44af06f2eb0) on top of the HEAD of the `sycl` branch (as of 7743e86f522) with a SYCLE kernel that calls `printf`, the compilation for the CUDA backend fails with
```
ptxas /tmp/fwyzard/main_oneapi-2cd1b3.s, line 516; error   : Call has wrong number of parameters
ptxas /tmp/fwyzard/main_oneapi-2cd1b3.s, line 721; error   : Call has wrong number of parameters
ptxas /tmp/fwyzard/main_oneapi-2cd1b3.s, line 890; error   : Call has wrong number of parameters
ptxas /tmp/fwyzard/main_oneapi-2cd1b3.s, line 1543; error   : Call has wrong number of parameters
ptxas /tmp/fwyzard/main_oneapi-2cd1b3.s, line 1643; error   : Call has wrong number of parameters
ptxas fatal   : Ptx assembly aborted due to errors
clang-11: error: ptxas command failed with exit code 255 (use -v to see invocation)
```

All errors point to similar PTX code:
```ptx
        call.uni (retval0),
        _Z18__spirv_ocl_printfPU3AS4Kcz,
        (
        param0,
        param1
        );
```

where `_Z18__spirv_ocl_printfPU3AS4Kcz` demangles to `__spirv_ocl_printf(char const AS4*, ...)`.

The same kernel compiles and runs with the OpenCL backend.

In case it's useful, the way I am using `printf` in kernel code is [here](https://github.com/fwyzard/pixel-standalone/blob/oneapi/rawtodigi_oneapi.cc#L17-L21) and e.g. [here](https://github.com/fwyzard/pixel-standalone/blob/oneapi/rawtodigi_oneapi.cc#L178).

The code compiles for the CUDA backend if I comment out the call to `cl::sycl::intel::experimental::printf`.

### PR DESCRIPTION
**Pull request by jchlanda**
Use `::printf` when not compiling for `__SPIR__`, this allows the use of `EmitNVPTXDevicePrintfCallExpr` which packs the var args and dispatches to CUDA's `vprintf`.

Fixes #1154

### CODE REVIEW

File: clang/lib/Sema/SemaSYCL.cpp [hunk 1]
```diff
@@ -420,6 +420,9 @@ static bool IsSyclMathFunc(unsigned BuiltinID) {
 bool Sema::isKnownGoodSYCLDecl(const Decl *D) {
   if (const FunctionDecl *FD = dyn_cast<FunctionDecl>(D)) {
     const IdentifierInfo *II = FD->getIdentifier();
+    if (FD->getBuiltinID() == Builtin::BIbuiltin__printf) {
+      return true;
+    }
```
Comment (bader) [inline clang/lib/Sema/SemaSYCL.cpp]:
```suggestion
    if (FD->getBuiltinID() == Builtin::BIbuiltin__printf)
      return true;
```

File: clang/lib/CodeGen/CGGPUBuiltin.cpp [hunk 2]
```diff
@@ -70,7 +70,8 @@ RValue
 CodeGenFunction::EmitNVPTXDevicePrintfCallExpr(const CallExpr *E,
                                                ReturnValueSlot ReturnValue) {
   assert(getTarget().getTriple().isNVPTX());
-  assert(E->getBuiltinCallee() == Builtin::BIprintf);
+  assert(E->getBuiltinCallee() == Builtin::BIbuiltin__printf ||
```
Comment (bader) [inline clang/lib/CodeGen/CGGPUBuiltin.cpp:73]: The function seems to process `printf` built-in already. Can't we use it instead of adding support for `__builtin_printf`?

File: clang/lib/CodeGen/CGGPUBuiltin.cpp [hunk 3]
```diff
@@ -118,8 +119,20 @@ CodeGenFunction::EmitNVPTXDevicePrintfCallExpr(const CallExpr *E,
...
+  // Check if the format specifier is in the constant address space, vprintf is
+  // oblivious to address spaces, so it would have to be casted away.
+  if (Args[0]
+          .getRValue(*this)
+          .getScalarVal()
+          ->getType()
+          ->getPointerAddressSpace() == 4) {
+    FormatSpecifier = Builder.CreateAddrSpaceCast(
+        FormatSpecifier, llvm::Type::getInt8PtrTy(Ctx));
+  }
```
Comment (bader) [inline clang/lib/CodeGen/CGGPUBuiltin.cpp:133]:
```suggestion
          ->getPointerAddressSpace() == 4)
    FormatSpecifier = Builder.CreateAddrSpaceCast(
        FormatSpecifier, llvm::Type::getInt8PtrTy(Ctx));
```

File: clang/lib/CodeGen/CGGPUBuiltin.cpp (hunk 2 above)
Comment (jchlanda) [reply clang/lib/CodeGen/CGGPUBuiltin.cpp]: That's a good point, done now.

**Comment by jchlanda** [comment]
Looks like the build might be broken, there are multiple failures to do with `hipMemsetD[8|16|32]Async` that were not introduced in this PR.

File: sycl/include/sycl/ext/oneapi/experimental/builtins.hpp [hunk 4]
```diff
@@ -62,10 +62,14 @@ namespace experimental {
...
 #ifdef __SYCL_DEVICE_ONLY__
+#ifdef __SPIR__
   return __spirv_ocl_printf(__format, args...);
 #else
   return ::printf(__format, args...);
-#endif
+#endif // __SPIR__
+#else
+  return ::printf(__format, args...);
+#endif // __SYCL_DEVICE_ONLY__
```
Comment (bader) [inline sycl/include/sycl/ext/oneapi/experimental/builtins.hpp:72]: I think this can be simplified to:
```c++
#if defined(__SYCL_DEVICE_ONLY__) && defined(__SPIR__)
  return __spirv_ocl_printf(__format, args...);
#else
  return ::printf(__format, args...);
#endif // defined(__SYCL_DEVICE_ONLY__) && defined(__SPIR__)
```

**Review by bader — COMMENTED** [review]
Looks much simpler. Just one more suggestion.
Could you update PR title, please?

File: sycl/include/sycl/ext/oneapi/experimental/builtins.hpp (hunk 4 above)
Comment (jchlanda) [reply sycl/include/sycl/ext/oneapi/experimental/builtins.hpp]: Yeap, done.

**Review by bader — APPROVED** [review]
Great. Thank you!

**Comment by jchlanda** [comment]
Is the Precommit failure something that I would need to look into?

**Review by elizabethandrews — COMMENTED** [review]
Can we add a FE test to verify change?

**Comment by bader** [comment]
> Is the Precommit failure something that I would need to look into?

I don't think so. Precommit doesn't run any tests on CUDA back-end and the failure in this particular is seems to be known flaky issue - it's the same as the second issue in this comment https://github.com/intel/llvm/pull/4281#issuecomment-896019361.

**Comment by jchlanda** [comment]
> Can we add a FE test to verify change?

Added in https://github.com/intel/llvm/pull/4293/commits/f7bbcc6d10832ec45fec34d9a8881a782ea264d1

**Review by bader — APPROVED** [review]

**Review by elizabethandrews — APPROVED** [review]

**Comment by bader** [comment]
@sergey-semenov, @intel/llvm-reviewers-runtime, ping.

**Review by sergey-semenov — APPROVED** [review]

**Comment by AerialMantis** [comment]
@premanandrao your suggestion makes sense, unfortunately @jchlanda is on leave for a few weeks, would you be okay with this change being made in a follow up pull request?

File: clang/test/CodeGenSYCL/nvptx-printf.cpp [hunk 5]
```diff
@@ -0,0 +1,18 @@
...
+
+#include "Inputs/sycl.hpp"
+
+#ifdef __SYCL_DEVICE_ONLY__
+#define CONSTANT __attribute__((opencl_constant))
+#else
+#define CONSTANT
+#endif
+
+static const CONSTANT char format_2[] = "Hello! %d %f\n";
```
Comment (bader) [inline clang/test/CodeGenSYCL/nvptx-printf.cpp:11]:
```suggestion
static const __SYCL_CONSTANT_AS char format_2[] = "Hello! %d %f\n";
```

**Review by bader — APPROVED** [review]

**Comment by bader** [comment]
> @premanandrao your suggestion makes sense, unfortunately @jchlanda is on leave for a few weeks, would you be okay with this change being made in a follow up pull request?

I've applied the suggestion. I think we can merge it, if tests pass.

**Comment by AerialMantis** [comment]
> I've applied the suggestion. I think we can merge it, if tests pass.

That works too, thanks @alexey-bataev

**Review by romanovvlad — APPROVED** [review]

File: clang/lib/Sema/SemaSYCL.cpp [hunk 6]
```diff
@@ -420,6 +420,8 @@ static bool IsSyclMathFunc(unsigned BuiltinID) {
 bool Sema::isKnownGoodSYCLDecl(const Decl *D) {
   if (const FunctionDecl *FD = dyn_cast<FunctionDecl>(D)) {
     const IdentifierInfo *II = FD->getIdentifier();
+    if (FD->getBuiltinID() == Builtin::BIprintf)
+      return true;
```
Comment (AlexeySachkov) [inline clang/lib/Sema/SemaSYCL.cpp:424]: Tagging @AaronBallman, @elizabethandrews and @premanandrao for awareness: this `if` should probably be extended to check if we are compiling for CUDA or not.

The thing is that `printf` built-in as-is won't be properly converted into SPIR-V and will cause JIT compilation errors on OpenCL backends.

Comment (AaronBallman) [reply clang/lib/Sema/SemaSYCL.cpp:424]: Changing it to check for CUDA makes sense to me, good catch!
