### PR TITLE
[SYCL] Set lexical context for generated OpenCL kernel function

### LINKED ISSUE #1015: ConstructOpenCLKernel doesn't set lexical context-
When doing ConstructOpenCLKernel, we don't set the current function/lexical context correctly, so getCurLexicalContext (or getCurFunctionDecl) fails, as we're in the TU-level at that point.  This function should set the function for diagnostics purposes (and other analysis purposes).

### PR DESCRIPTION
**Pull request by erichkeane**
When doing ConstructOpenCLKernel, we don't set the current 
function/lexical context correctly, so getCurLexicalContext 
(or getCurFunctionDecl) fails, as we're in the TU-level at that point. 
This function should set the function for diagnostics purposes (and 
other analysis purposes).

At the moment, this isn't causing any problems (particularly since the
diagnostic changes previously made don't try to diagnose during this),
however this is likely something we would notice later.

Start a RAII container to set the current function decl to the kernel.

Fixes #1015.

Signed-off-by: Erich Keane <erich.keane@intel.com>

### CODE REVIEW

File: clang/lib/Sema/SemaSYCL.cpp [hunk 1]
```diff
@@ -1285,6 +1285,8 @@ void Sema::ConstructOpenCLKernel(FunctionDecl *KernelCallerFunc,
   FunctionDecl *OpenCLKernel =
       CreateOpenCLKernelDeclaration(getASTContext(), Name, ParamDescs);
 
+  ContextRAII FuncContext(*this, OpenCLKernel);
```
Comment (Fznamznon) [inline clang/lib/Sema/SemaSYCL.cpp]: Do we really need this? We disabled diagnosing during OpenCL kernel generation, is it possible that we once enable it?

Comment (erichkeane) [reply clang/lib/Sema/SemaSYCL.cpp]: At the moment, I no longer have a true motivating example. However, this is a bug we have worked around a few times, so I suspect we will need this fixed eventually.

Additionally, this is one of the conditions where getLexicalContext gave us not a Function Decl, so now that this is fixed, we know !FD means exactly what it should, that we are evaluating a global (and this can properly handle that once we figure that out).

Comment (Fznamznon) [reply clang/lib/Sema/SemaSYCL.cpp]: Okay, sounds reasonable for me.

**Comment by bader** [comment]
> It doesn't affect anything right now, but I'm not sure that it is NFC.

I've updated the PR subject and description. 

@Fznamznon, @erichkeane are you okay if I use them for the commit message?

**Comment by erichkeane** [comment]
> 
> 
> > It doesn't affect anything right now, but I'm not sure that it is NFC.
> 
> I've updated the PR subject and description.
> 
> @Fznamznon, @erichkeane are you okay if I use them for the commit message?

Yep, that looks good to me.
