### PR TITLE
[SYCL] Throw correct exception when passing unbound accessor to command 

### LINKED ISSUE #3078: [SYCL] Poor error reporting for unbound placeholder accessor
Hello!

This is not a bug, but a case of a very unclear error message from the SYCL runtime in case of incorrect code.

**Example code**

Please note, that the code is invalid since a placeholder accessor is not bound using `cgh.require` before accessing it in a kernel.
While such a mistake is not hard to notice here, it might easily creep into complicated kernels with multiple accessors.

```cpp
#include <CL/sycl.hpp>

using cl::sycl::access::mode;
using cl::sycl::access::placeholder;
using cl::sycl::access::target;

template <class T, enum mode Mode>
using PlaceholderAccessor =
    cl::sycl::accessor<T, 1, Mode, target::global_buffer, placeholder::true_t>;

auto myKernel(cl::sycl::handler &cgh,
              PlaceholderAccessor<int, mode::write> data) {
  // Oops, forgot to call cgh.require(data) here
  return [=](cl::sycl::item<1> itemIdx) {
    const int v = itemIdx.get_linear_id();
    data[v] = v;
  };
}

class KernelName;

int main() {
  cl::sycl::device dev{cl::sycl::gpu_selector()};
  cl::sycl::queue q{dev};
  cl::sycl::buffer<int, 1> buffer(1);
  cl::sycl::event e = q.submit([&](cl::sycl::handler &cgh) {
    auto kernel = myKernel(cgh, buffer);
    cgh.parallel_for<KernelName>(1, kernel);
  });
  e.wait_and_throw();
  return 0;
}
```

**Current output**

The error thrown when running the code above (using d1d6c5df34dd032dca9196856202be519fcf1b99 version of intel/llvm) is rather cryptic (#1927 is mildly related), and requires digging through the code of the runtime:

```
$ clang++ test.cpp -fsycl -o test && ./test
terminate called after throwing an instance of 'cl::sycl::runtime_error'
  what():  Alloca for command not found -59 (CL_INVALID_OPERATION)
Aborted (core dumped)
```

**Expectations**

Neither SYCL 1.2.1 nor 2020-provisional specs are explicit about what happens when using a placeholder accessor in the kernel without requiring it. So it seems to fall into undefined/unspecified territory.

However, the current behavior leaves a lot to be desired. A more explicit run-time error, at least suggesting that the issue is related to accessors, would improve things drastically.

Something like try-catch-rethrow [here](https://github.com/intel/llvm/blob/d1d6c5df34dd032dca9196856202be519fcf1b99/sycl/source/detail/scheduler/commands.cpp#L1664) might be a quick fix that will already help a lot.

Ideally, one would prefer to get a compile-time warning in such clear-cut cases as the code above.

### PR DESCRIPTION
**Pull request by maarquitos14**
According to 4.7.6.9 of SYCL2020 spec, if a placeholder accessor
is passed to a command without being bound to a command group, an
exception should be thrown. Prior to this change, the exception
was only thrown if an unbound placeholder accessor is used, not
only passed. Also, prior to this change, if we passed one unbound
accessor and one (or more) bound accessors to a command, the
exception thrown was incorrect.

Closes #3078.

### CODE REVIEW

**Comment by maarquitos14** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1549

**Comment by maarquitos14** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1549

**Comment by maarquitos14** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1549

**Comment by maarquitos14** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1549

**Comment by maarquitos14** [comment]
Friendly ping @sergey-semenov @cperkinsintel @intel/llvm-reviewers-runtime

File: sycl/source/detail/scheduler/commands.cpp [hunk 1]
```diff
@@ -243,6 +247,15 @@ static void flushCrossQueueDeps(const std::vector<EventImplPtr> &EventImpls,
   }
 }
 
+static AllocaCommandBase *
+allocaCmdGetOrThrow(std::optional<AllocaCommandBase *> allocaCmd) {
```
Comment (sergey-semenov) [inline sycl/source/detail/scheduler/commands.cpp:251]: Seeing as this is only called in conjunction with `getAllocaForReq`, I would suggest to replace this with `getAllocaForReqOrThrow` that would just call `getAllocaForReq` and make the check.

File: sycl/source/detail/scheduler/commands.hpp [hunk 2]
```diff
@@ -570,7 +570,8 @@ pi_int32 enqueueImpKernel(
     const std::shared_ptr<detail::kernel_impl> &MSyclKernel,
     const std::string &KernelName, const detail::OSModuleHandle &OSModuleHandle,
     std::vector<RT::PiEvent> &RawEvents, RT::PiEvent *OutEvent,
-    const std::function<void *(Requirement *Req)> &getMemAllocationFunc);
+    const std::function<std::optional<void *>(Requirement *Req)>
```
Comment (sergey-semenov) [inline sycl/source/detail/scheduler/commands.hpp:573]: `std::optional` seems redundant for a pointer type, we should probably just use `nullptr` to denote a "missing" value instead. The same goes for `getAllocaReq`.

File: sycl/source/detail/scheduler/commands.cpp [hunk 3]
```diff
@@ -110,8 +110,12 @@ static void applyFuncOnFilteredArgs(
           ++NextTrueIndex;
       LastIndex = Arg.MIndex;
 
-      if (EliminatedArgMask[Arg.MIndex])
+      if (EliminatedArgMask[Arg.MIndex]) {
+        if (Arg.MType == kernel_param_kind_t::kind_accessor)
```
Comment (sergey-semenov) [inline sycl/source/detail/scheduler/commands.cpp:114]: This runs contrary to what I would expect from a function called `applyFuncOnFilteredArgs`. Moving out a part of this filtering to the function object passed by the callee seems wrong to me (especially considering that this filtering is missing from the call site at `ExecCGCommand::emitInstrumentationData` which would result in invalid xpti metadata).

**Review by sergey-semenov — CHANGES_REQUESTED** [review]

File: sycl/source/detail/scheduler/commands.cpp [hunk 4]
```diff
@@ -1397,13 +1397,22 @@ void MemCpyCommand::printDot(std::ostream &Stream) const {
   }
 }
 
-AllocaCommandBase *ExecCGCommand::getAllocaForReq(Requirement *Req) {
+AllocaCommandBase *ExecCGCommand::getAllocaForReqOrThrow(Requirement *Req) {
+  auto allocaCmd = getAllocaForReq(Req);
```
Comment (AlexeySachkov) [inline sycl/source/detail/scheduler/commands.cpp:1401]:
```suggestion
  auto AllocaCmd = getAllocaForReq(Req);
```

Note: I'm not entirely sure if we have a requirement for RT code for local variables to be in `CamelCase`. But the surrounding code seem to follow that code style

File: sycl/source/detail/scheduler/commands.cpp [hunk 5]
```diff
@@ -2033,6 +2038,22 @@ static pi_result SetKernelParamsAndLaunch(
     }
   };
 
+  for (auto &arg : Args) {
+    if (arg.MType == kernel_param_kind_t::kind_accessor) {
```
Comment (AlexeySachkov) [inline sycl/source/detail/scheduler/commands.cpp:2042]: What about converting this into an early exist to reduce amount of indentation levels?

File: sycl/source/detail/scheduler/commands.cpp [hunk 6]
```diff
@@ -2033,6 +2038,22 @@ static pi_result SetKernelParamsAndLaunch(
     }
   };
 
+  for (auto &arg : Args) {
```
Comment (AlexeySachkov) [inline sycl/source/detail/scheduler/commands.cpp:2041]: Out of curiosity: can we also mark `arg` as `cosnt`? Though I assume it may not be easy as it will require adding `const` into several more places

File: sycl/source/detail/scheduler/commands.cpp [hunk 7]
```diff
@@ -2033,6 +2038,22 @@ static pi_result SetKernelParamsAndLaunch(
...
+    if (arg.MType == kernel_param_kind_t::kind_accessor) {
+      if (getMemAllocationFunc == nullptr)
```
Comment (AlexeySachkov) [inline sycl/source/detail/scheduler/commands.cpp:2043]: Why not simpler `if (!getMemAllocationFunc)`?

**Review by AlexeySachkov — COMMENTED** [review]
Why there are not test changes in this PR? There should either be a new test for a missing case this PR fixes or a change to enable previously disabled test (due to missing case)

**Comment by sergey-semenov** [comment]
Actually, isn't handling this right before enqueue a bit late? The specification requires a synchronous exception in this case, which we won't get if the submitted command is blocked. It would probably be better to throw this exception from `handler::finalize()`.

File: sycl/source/detail/scheduler/commands.cpp (hunk 4 above)
Comment (maarquitos14) [reply sycl/source/detail/scheduler/commands.cpp:1401]: > Why there are not test changes in this PR? There should either be a new test for a missing case this PR fixes or a change to enable previously disabled test (due to missing case)

The new tests are in this [PR](https://github.com/intel/llvm-test-suite/pull/1549/) in `llvm-test-suite`.

**Comment by maarquitos14** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1549

**Review by sergey-semenov — CHANGES_REQUESTED** [review]

File: sycl/source/handler.cpp [hunk 8]
```diff
@@ -94,6 +94,26 @@ event handler::finalize() {
...
   MIsFinalized = true;
 
+  // According to 4.7.6.9 of SYCL2020 spec, if a placeholder accessor is passed
+  // to a command without being bound to a command group, an exception should
+  // be thrown. There should be as many requirements as unique accessors,
+  // otherwise some of the accessors are unbound, and thus we throw.
+  {
+    // A counter is not good enough since we can have the same accessor several
+    // times as arg
+    std::unordered_set<void *> accessors;
```
[the remark this answers is not in the document]
Comment (sergey-semenov) [reply sycl/source/handler.cpp:104]: Discussed offline, I was under the misconception that `SYCLMemObj` has anything to do with whether the accessor is bound or not. Never mind.

**Review by sergey-semenov — APPROVED** [review]

**Review by AlexeySachkov — APPROVED** [review]
I don't have objections from my side
