### PR TITLE
[SYCL] Fix alignment of emulated specialization constants

### LINKED ISSUE #5911: [CUDA] Multiple cts/specialization_constants_* tests crashed on build with error: Assertion `llvm::isSafeToDestroyConstant(*It) && "Cannot remove an element of initializer of llvm.used global"' failed.
**Describe the bug**
[CUDA] Multiple cts/specialization_constants_* tests crashed on build with error: Assertion `llvm::isSafeToDestroyConstant(*It) && "Cannot remove an element of initializer of llvm.used global"' failed.

**To Reproduce**
1. Get SYCL with CUDA support ([GSG](https://intel.github.io/llvm-docs/GetStartedGuide.html)) and ([SYCL-CTS](https://github.com/KhronosGroup/SYCL-CTS))

2. Build CTS tests
```
cd SYCL-CTS
mkdir build && cd build
cmake -G "Ninja" -DSYCL_IMPLEMENTATION=Intel_SYCL -DINTEL_SYCL_ROOT=<path to built sycl> -DOpenCL_LIBRARY=<path to built sycl>/lib/libOpenCL.so -DOpenCL_INCLUDE_DIR=<path to built sycl>/include/sycl -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS_RELEASE=" " -DINTEL_SYCL_FLAGS="-fsycl-device-code-split=per_source;-Wno-deprecated-declarations;-fsycl;-fsycl-unnamed-lambda" -DCMAKE_EXE_LINKER_FLAGS=" -Wl,-no-relax " -DINTEL_SYCL_TRIPLE=nvptx64-nvidia-cuda -DSYCL_CTS_ENABLE_OPENCL_INTEROP_TESTS=Off -DSYCL_CTS_ENABLE_DOUBLE_TESTS=On -DSYCL_CTS_ENABLE_HALF_TESTS=On ..
ninja -j 7 -k 0 -v test_specialization_constants
```
Error message:
```
FAILED: bin/test_specialization_constants 
: && <path to built sycl>/bin/clang++ -DSYCL2020_CONFORMANT_APIS -DSYCL2020_DISABLE_DEPRECATION_WARNINGS -D__SYCL_DISABLE_PARALLEL_FOR_RANGE_ROUNDING__ -ffp-model=precise      -Wl,-no-relax    -fsycl -sycl-std=2020 -fsycl-device-code-split=per_source -Wno-deprecated-declarations -fsycl-unnamed-lambda -fsycl-targets=nvptx64-nvidia-cuda tests/specialization_constants/CMakeFiles/test_specialization_constants_objects.dir/specialization_constants_class_with_member_fun.cpp.o tests/specialization_constants/CMakeFiles/test_specialization_constants_objects.dir/specialization_constants_defined_various_ways_core.cpp.o tests/specialization_constants/CMakeFiles/test_specialization_constants_objects.dir/specialization_constants_defined_various_ways_fp16.cpp.o tests/specialization_constants/CMakeFiles/test_specialization_constants_objects.dir/specialization_constants_defined_various_ways_fp64.cpp.o tests/specialization_constants/CMakeFiles/test_specialization_constants_objects.dir/specialization_constants_exceptions_throwing_core.cpp.o tests/specialization_constants/CMakeFiles/test_specialization_constants_objects.dir/specialization_constants_exceptions_throwing_fp16.cpp.o tests/specialization_constants/CMakeFiles/test_specialization_constants_objects.dir/specialization_constants_exceptions_throwing_fp64.cpp.o tests/specialization_constants/CMakeFiles/test_specialization_constants_objects.dir/specialization_constants_external_core.cpp.o tests/specialization_constants/CMakeFiles/test_specialization_constants_objects.dir/specialization_constants_external_fp16.cpp.o tests/specialization_constants/CMakeFiles/test_specialization_constants_objects.dir/specialization_constants_external_fp64.cpp.o tests/specialization_constants/CMakeFiles/test_specialization_constants_objects.dir/specialization_constants_multiple_core.cpp.o tests/specialization_constants/CMakeFiles/test_specialization_constants_objects.dir/specialization_constants_multiple_fp16.cpp.o tests/specialization_constants/CMakeFiles/test_specialization_constants_objects.dir/specialization_constants_multiple_fp64.cpp.o tests/specialization_constants/CMakeFiles/test_specialization_constants_objects.dir/specialization_constants_same_command_group_core.cpp.o tests/specialization_constants/CMakeFiles/test_specialization_constants_objects.dir/specialization_constants_same_command_group_fp16.cpp.o tests/specialization_constants/CMakeFiles/test_specialization_constants_objects.dir/specialization_constants_same_command_group_fp64.cpp.o tests/specialization_constants/CMakeFiles/test_specialization_constants_objects.dir/specialization_constants_same_name_inter_link_1st_tu_core.cpp.o tests/specialization_constants/CMakeFiles/test_specialization_constants_objects.dir/specialization_constants_same_name_inter_link_1st_tu_fp16.cpp.o tests/specialization_constants/CMakeFiles/test_specialization_constants_objects.dir/specialization_constants_same_name_inter_link_1st_tu_fp64.cpp.o tests/specialization_constants/CMakeFiles/test_specialization_constants_objects.dir/specialization_constants_same_name_inter_link_2nd_tu_core.cpp.o tests/specialization_constants/CMakeFiles/test_specialization_constants_objects.dir/specialization_constants_same_name_inter_link_2nd_tu_fp16.cpp.o tests/specialization_constants/CMakeFiles/test_specialization_constants_objects.dir/specialization_constants_same_name_inter_link_2nd_tu_fp64.cpp.o tests/specialization_constants/CMakeFiles/test_specialization_constants_objects.dir/specialization_constants_same_name_stress_core.cpp.o tests/specialization_constants/CMakeFiles/test_specialization_constants_objects.dir/specialization_constants_same_name_stress_fp16.cpp.o tests/specialization_constants/CMakeFiles/test_specialization_constants_objects.dir/specialization_constants_same_name_stress_fp64.cpp.o tests/specialization_constants/CMakeFiles/test_specialization_constants_objects.dir/specialization_constants_separate_unit.cpp.o tests/specialization_constants/CMakeFiles/test_specialization_constants_objects.dir/specialization_constants_via_handler_core.cpp.o tests/specialization_constants/CMakeFiles/test_specialization_constants_objects.dir/specialization_constants_via_handler_fp16.cpp.o tests/specialization_constants/CMakeFiles/test_specialization_constants_objects.dir/specialization_constants_via_handler_fp64.cpp.o tests/common/CMakeFiles/main_function_object.dir/main.cpp.o -o bin/test_specialization_constants  -Wl,-rpath,<path to built sycl>/lib util/libutil.a oclmath/liboclmath.a vendor/Catch2/src/libCatch2.a <path to built sycl>/lib/libOpenCL.so -lpthread && :
sycl-post-link: llvm.src/llvm/tools/sycl-post-link/sycl-post-link.cpp:856: bool {anonymous}::removeSYCLKernelsConstRefArray(llvm::GlobalVariable*): Assertion `llvm::isSafeToDestroyConstant(*It) && "Cannot remove an element of initializer of llvm.used global"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: sycl-post-link -split=source -emit-param-info -emit-program-metadata -symbols -emit-exported-symbols -split-esimd -lower-esimd -O2 -spec-const=default -o /tmp/specialization_constants_class_with_member_fun-b583ea/specialization_constants_class_with_member_fun-sm_50.bc /tmp/specialization_constants_class_with_member_fun-e212e6/specialization_constants_class_with_member_fun-sm_50.bc
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
sycl-post-link(+0x2a74b4)[0x56016f79c4b4]
sycl-post-link(+0x2a552e)[0x56016f79a52e]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0)[0x7f03bd8543c0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7f03bd0f818b]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7f03bd0d7859]
/lib/x86_64-linux-gnu/libc.so.6(+0x25729)[0x7f03bd0d7729]
/lib/x86_64-linux-gnu/libc.so.6(+0x36f36)[0x7f03bd0e8f36]
sycl-post-link(+0x96643)[0x56016f58b643]
sycl-post-link(+0x6ecd0)[0x56016f563cd0]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f03bd0d90b3]
sycl-post-link(+0x8460e)[0x56016f57960e]
clang++: error: unable to execute command: Aborted (core dumped)
clang++: error: sycl-post-link command failed due to signal (use -v to see invocation)
clang version 15.0.0 (https://github.com/intel/llvm.git 1fe5eaa7455f25a1475794bedc42cc73e9b07bd1)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: <path to built sycl>/bin
clang++: note: diagnostic msg: Error generating preprocessed source(s).
ninja: build stopped: cannot make progress due to previous errors.
```

**Environment**

- OS: Linux
- Target device and vendor: Nvidia GPU
- DPC++ version: https://github.com/intel/llvm.git 1fe5eaa7455f25a1475794bedc42cc73e9b07bd1
- CUDA version: 
```
nvidia-smi
+-----------------------------------------------------------------------------+
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
```

### PR DESCRIPTION
**Pull request by npmiller**
This patch solves #6093, and finishes to fix #5911 

It doesn't change anything for native specialization constants, but correctly aligns emulated specialization constants based on type requirements.

Emulated specialization constant don't use the `CompositeOffset` mechanism, so this patch re-uses this field to communicate the necessary padding from the compiler pass in `sycl-post-link` to the runtime to ensure correct alignment.

With this patch the SYCL-CTS specialization constant tests are all passing with the CUDA plugin:
```
% ./bin/test_specialization_constants  
===============================================================================
All tests passed (56 assertions in 46 test cases)
```

Note this is on top of #6125

### CODE REVIEW

**Comment by aelovikov-intel** [comment]
It seems that some changes are done in sync in both sycl-post-link and inside SYCL runtime. What would be the behavior if we'd use the compilation toolchain (including sycl-post-link) before this change and runtime after it? Is it correct to assume that nothing that wouldn't be failing with old runtime would fail in this scenario?

**Comment by npmiller** [comment]
> It seems that some changes are done in sync in both sycl-post-link and inside SYCL runtime. What would be the behavior if we'd use the compilation toolchain (including sycl-post-link) before this change and runtime after it? Is it correct to assume that nothing that wouldn't be failing with old runtime would fail in this scenario?

I believe that would work fine yes.

This patch doesn't change the format of how the specialization constants are communicated between the compilation and the runtime, it simply re-uses a field that's unused for emulated spec constants to communicate the padding, and that field was previously always set to `0` for emulated specialization constants.

So the new runtime using an old binary will read that field and add it as padding but since it's always `0` it will end up with the exact same layout as the old runtime.

File: sycl/source/detail/program_manager/program_manager.cpp [hunk 1]
```diff
@@ -1855,24 +1855,22 @@ device_image_plain ProgramManager::build(const device_image_plain &DeviceImage,
...
-
-        for (const auto &DescPair : SpecConstData) {
-          for (const device_image_impl::SpecConstDescT &SpecIDDesc :
-               DescPair.second) {
-            if (SpecIDDesc.IsSet) {
-              Plugin.call<PiApiKind::piextProgramSetSpecializationConstant>(
-                  NativePrg, SpecIDDesc.ID, SpecIDDesc.Size,
-                  SpecConsts.data() + SpecIDDesc.BlobOffset);
-            }
+    if (!DeviceCodeWasInCache &&
```
Comment (asudarsa) [inline sycl/source/detail/program_manager/program_manager.cpp:1858]: I do not see any changes (other than some format changes) here. Can we do away with this change? Thanks

File: sycl/source/detail/device_image_impl.hpp [hunk 2]
```diff
@@ -278,20 +278,38 @@ class device_image_impl {
...
+            const unsigned OffsetFromLast = /*Offset*/ It[1] - LocalOffset;
+            BlobOffset += OffsetFromLast;
+
+            // Composites may have a special padding element at the end which
+            // should not have a descriptor. These padding elements all have max
+            // ID value.
+            if (It[0] != std::numeric_limits<std::uint32_t>::max()) {
+              // The map is not locked here because updateSpecConstSymMap() is
+              // only supposed to be called from c'tor.
+              MSpecConstSymMap[std::string{SCName}].push_back(
```
Comment (asudarsa) [inline sycl/source/detail/device_image_impl.hpp:292]: This call can be moved out of the if-then-else (nit pick). Thanks

File: llvm/tools/sycl-post-link/SpecConstants.cpp [hunk 3]
```diff
@@ -770,14 +773,27 @@ PreservedAnalyses SpecConstantsPass::run(Module &M,
           auto Ins = OffsetMap.insert(std::make_pair(SymID, NextOffset));
           IsNewSpecConstant = Ins.second;
           unsigned CurrentOffset = Ins.first->second;
-          if (IsNewSpecConstant) {
-            unsigned Size = M.getDataLayout().getTypeStoreSize(SCTy);
 
+          unsigned Size = M.getDataLayout().getTypeStoreSize(SCTy);
+          unsigned Align = M.getDataLayout().getABITypeAlignment(SCTy);
+
+          // Ensure the specialization constant is properly algined
```
Comment (asudarsa) [inline llvm/tools/sycl-post-link/SpecConstants.cpp:780]: Typo: algined -> aligned

File: sycl/source/detail/program_manager/program_manager.cpp (hunk 1 above)
Comment (npmiller) [reply sycl/source/detail/program_manager/program_manager.cpp:1858]: There is a change, the whole block is now conditioned on `InputImpl->get_bin_image_ref()->supportsSpecConstants()` when before it was only the call to `enableITTAnnotationsIfNeeded`, this is necessary because `piextProgramSetSpecializationConstant` is only supposed to be called for native specialization constants.

It's a little hard to see because of the way it was written originally, "one-line" if with no brackets followed by a scope.

Comment (npmiller) [reply sycl/source/detail/program_manager/program_manager.cpp:1858]: Also note that this is part of https://github.com/intel/llvm/pull/6125 , maybe I should fuse the two MRs.

File: sycl/source/detail/device_image_impl.hpp (hunk 2 above)
Comment (npmiller) [reply sycl/source/detail/device_image_impl.hpp]: Extracted it and also re-worked this part of the code so it's more readable, mainly re-named the iterators.

**Comment by npmiller** [comment]
Rebased since https://github.com/intel/llvm/pull/6125 was merged, this now only contains the changes relating to the alignment issue.

File: sycl/source/detail/device_image_impl.hpp [hunk 4]
```diff
@@ -278,21 +278,38 @@ class device_image_impl {
...
         unsigned LocalOffset = 0;
         while (It != End) {
-          // Make sure that alignment is correct in blob.
-          const unsigned OffsetFromLast = /*Offset*/ It[1] - LocalOffset;
-          BlobOffset += OffsetFromLast;
+          unsigned int ID = It[0];
+          unsigned int CompositeOffset = It[1];
+          unsigned int Size = It[2];
+
+          if (MBinImage->supportsSpecConstants()) {
```
Comment (steffenlarsen) [inline sycl/source/detail/device_image_impl.hpp:285]: IIRC this will not be enough to make the distinction. The check will always return true for SPIR-V binaries, but even they may be using emulated spec-consts if `-spec-const=rt` was passed to sycl-post-link.

I am not certain there is a good way to check which version of spec-constants were generated. It would be nice if there was a way to mark the data entry, but I don't believe there is currently. An alternative is to use the existing padding representation, i.e. through a spec-const entry with `uint32_t` max ID (see below).

Comment (npmiller) [reply sycl/source/detail/device_image_impl.hpp]: That's a very good point, I've had another look at this and using the padding elements I was able to make it work with no changes in the runtime at all, the current patch should reflect that.

Comment (steffenlarsen) [reply sycl/source/detail/device_image_impl.hpp]: Great! In that case, runtime changes LGTM! 😄

File: llvm/tools/sycl-post-link/SpecConstants.cpp [hunk 5]
```diff
@@ -772,6 +773,66 @@ PreservedAnalyses SpecConstantsPass::run(Module &M,
...
+              // The spec constant map can't be empty as the first offset is 0
+              // and so it can't be misaligned.
+              assert(!SCMetadata.empty() &&
+                     "Cannot add padding to first spec constant");
+
+              // To communicate the padding to the runtime, update the metadata
+              // node of the previous spec constant to append a padding node. It
+              // can't be added in front of the current spec constant, as doing
+              // so would require the spec constant node to have a non-zero
+              // CompositeOffset which breaks accessing it in the runtime.
```
Comment (steffenlarsen) [inline llvm/tools/sycl-post-link/SpecConstants.cpp:797]: What part of the runtime makes this restriction? I am not opposed to appending it to the previous entry, but it would be a little cleaner to have it attached to the entry forcing the alignment.

Comment (npmiller) [reply llvm/tools/sycl-post-link/SpecConstants.cpp:797]: If there's two metadata nodes and the second one has a `CompositeOffset` of `0`, the `OffsetFromLast` here goes negative and it causes issues:

* https://github.com/intel/llvm/blob/sycl/sycl/source/detail/device_image_impl.hpp#L282

And if we set the `CompositeOffset` correctly, then reading/writing the data won't work properly for emulated spec constants as it offsets the input data with it, see here:

* https://github.com/intel/llvm/blob/sycl/sycl/source/detail/device_image_impl.hpp#L131

So appending the padding works because it can have a `CompositeOffset` as it's not accessed, but putting it in front doesn't because then the data node needs a non-null `CompositeOffset`.

**Review by steffenlarsen — APPROVED** [review]

File: llvm/tools/sycl-post-link/SpecConstants.cpp [hunk 6]
```diff
@@ -772,6 +773,66 @@ PreservedAnalyses SpecConstantsPass::run(Module &M,
...
+              Padding = Size - CurrentOffset % Align;
+
+              // Update offsets.
+              NextOffset += Padding;
+              CurrentOffset += Padding;
+              OffsetMap[SymID] = NextOffset;
+
+              // The spec constant map can't be empty as the first offset is 0
+              // and so it can't be misaligned.
+              assert(!SCMetadata.empty() &&
```
Comment (kbobrovs) [inline llvm/tools/sycl-post-link/SpecConstants.cpp:790]: I would also suggest to add assert(CurrentOffset % Align == 0, "alignment calculation error");

File: llvm/tools/sycl-post-link/SpecConstants.cpp [hunk 7]
```diff
@@ -772,6 +773,66 @@ PreservedAnalyses SpecConstantsPass::run(Module &M,
           unsigned CurrentOffset = Ins.first->second;
           if (IsNewSpecConstant) {
             unsigned Size = M.getDataLayout().getTypeStoreSize(SCTy);
+            unsigned Align = M.getDataLayout().getABITypeAlignment(SCTy);
+
+            // Ensure correct alignment
+            if (CurrentOffset % Align != 0) {
+              // Compute necessary padding to correctly align the constant.
+              Padding = Size - CurrentOffset % Align;
```
[the remark this answers is not in the document]
Comment (npmiller) [reply llvm/tools/sycl-post-link/SpecConstants.cpp]: Good catch! It should be `Align` instead of `Size` here, fixed that and added the assert as suggested below.

File: llvm/tools/sycl-post-link/SpecConstants.cpp [hunk 8]
```diff
@@ -772,6 +773,69 @@ PreservedAnalyses SpecConstantsPass::run(Module &M,
           unsigned CurrentOffset = Ins.first->second;
           if (IsNewSpecConstant) {
             unsigned Size = M.getDataLayout().getTypeStoreSize(SCTy);
+            unsigned Align = M.getDataLayout().getABITypeAlignment(SCTy);
+
+            // Ensure correct alignment
+            if (CurrentOffset % Align != 0) {
+              // Compute necessary padding to correctly align the constant.
+              Padding = Align - CurrentOffset % Align;
```
[the remark this answers is not in the document]
Comment (kbobrovs) [reply llvm/tools/sycl-post-link/SpecConstants.cpp:781]: I take this back. There is a check `if (CurrentOffset % Align != 0)` above, missed it

**Review by kbobrovs — APPROVED** [review]

**Review by asudarsa — APPROVED** [review]
LGTM. Thanks

**Review by steffenlarsen — APPROVED** [review]
