### PR TITLE
[SYCL][CUDA] Update code when llvm.used is removed 

### LINKED ISSUE #4294: Clang crashes since last pulldowns when building shared objects
**Describe the bug**
Since last week I'm experiencing crashes when building SYCL projects. All the crashes happens when linking the SYCL back-end of that library into a shared object. 

When targeting the CUDA back-end, I get the following crashes:
I get, when building with `-Og`:
```
While deleting: %"class._ZTSN2cl4sycl5rangeILi3EEE.cl::sycl::range" ()* %
Use still stuck around after Def is destroyed:i8* bitcast (%"class._ZTSN2cl4sycl5rangeILi3EEE.cl::sycl::range" ()* <badref> to i8*)
Use still stuck around after Def is destroyed:  %call = call %"class._ZTSN2cl4sycl5rangeILi3EEE.cl::sycl::range" <badref>() #25, !dbg !58
clang-14: /home/michel/sycl_workspace/llvm/llvm/lib/IR/Value.cpp:103: llvm::Value::~Value(): Assertion `materialized_use_empty() && "Uses remain when a value is destroyed!"' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /home/michel/sycl_workspace/deploy/bin/clang-14 -cc1 -triple nvptx64-nvidia-cuda -aux-triple x86_64-unknown-linux-gnu -fsycl-is-device -fdeclare-spirv-builtins -sycl-std=2020 -fsycl-std-layout-kernel-params -S -disable-free -main-file-name zfp.c.o -mrelocation-model pic -pic-level 2 -fhalf-no-semantic-interposition -mframe-pointer=all -ffp-contract=on -fno-rounding-math -fno-verbose-asm -no-integrated-as -aux-target-cpu x86-64 -internal-isystem /home/michel/sycl_workspace/deploy/bin/../include/sycl -internal-isystem /home/michel/sycl_workspace/deploy/bin/../include -mlink-builtin-bitcode /home/michel/sycl_workspace/deploy/lib/clang/14.0.0/../../clc/libspirv-nvptx64--nvidiacl.bc -mlink-builtin-bitcode /usr/local/cuda-11.4/nvvm/libdevice/libdevice.10.bc -target-feature +ptx72 -target-sdk-version=11.2 -target-cpu sm_75 -mllvm -treat-scalable-fixed-error-as-warning -debug-info-kind=line-directives-only -dwarf-version=2 -debugger-tuning=gdb -fno-dwarf-directory-asm -v -resource-dir /home/michel/sycl_workspace/deploy/lib/clang/14.0.0 -Og -Wall -Wextra -Wshadow -Wdouble-promotion -Winit-self -Wuninitialized -Wmissing-declarations -Woverloaded-virtual -Wall -Wextra -Wcast-align -Wcast-qual -Wctor-dtor-privacy -Wdisabled-optimization -Wformat=2 -Winit-self -Wmissing-declarations -Wmissing-include-dirs -Woverloaded-virtual -Wredundant-decls -Wshadow -Wsign-conversion -Wsign-promo -Wstrict-overflow=5 -Wno-c++20-extensions -Wno-undef -Wno-unused -Wno-unused-parameter -Wno-unknown-cuda-version -pedantic -std=c++20 -fdebug-compilation-dir=/tmp/tmp.QgqHvAUwXa/cmake-build-debug/src -ferror-limit 19 -fgnuc-version=4.2.1 -fno-implicit-modules -fcolor-diagnostics -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/zfp-f738b8-d50538.s -x ir /tmp/zfp-350792.bc
1.	Code generation
2.	Running pass 'Add implicit SYCL global offset' on module '/tmp/zfp-350792.bc'.
```

And when building for release with `-O2`, the previous error disappear and I get this one instead:
```
clang-14: /home/michel/sycl_workspace/llvm/llvm/lib/Target/NVPTX/SYCL/LocalAccessorToSharedMemory.cpp:206: llvm::Function *(anonymous namespace)::LocalAccessorToSharedMemory::ProcessFunction(llvm::Module &, llvm::Function *): Assertion `F->use_empty()' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /home/michel/sycl_workspace/deploy/bin/clang-14 -cc1 -triple nvptx64-nvidia-cuda -aux-triple x86_64-unknown-linux-gnu -fsycl-is-device -fdeclare-spirv-builtins -sycl-std=2020 -fsycl-std-layout-kernel-params -S -disable-free -main-file-name zfp.c.o -mrelocation-model pic -pic-level 2 -fhalf-no-semantic-interposition -mframe-pointer=all -ffp-contract=on -fno-rounding-math -fno-verbose-asm -no-integrated-as -aux-target-cpu x86-64 -internal-isystem /home/michel/sycl_workspace/deploy/bin/../include/sycl -internal-isystem /home/michel/sycl_workspace/deploy/bin/../include -mlink-builtin-bitcode /home/michel/sycl_workspace/deploy/lib/clang/14.0.0/../../clc/libspirv-nvptx64--nvidiacl.bc -mlink-builtin-bitcode /usr/local/cuda-11.4/nvvm/libdevice/libdevice.10.bc -target-feature +ptx72 -target-sdk-version=11.2 -target-cpu sm_75 -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -fno-dwarf-directory-asm -resource-dir /home/michel/sycl_workspace/deploy/lib/clang/14.0.0 -O3 -Wno-unknown-cuda-version -std=c++20 -fdebug-compilation-dir=/tmp/tmp.QgqHvAUwXa/cmake-build-release/src -ferror-limit 19 -fgnuc-version=4.2.1 -fno-implicit-modules -fcolor-diagnostics -vectorize-loops -vectorize-slp -o /tmp/zfp-f9854a-16efb3.s -x ir /tmp/zfp-4c499c.bc
1.	Code generation
2.	Running pass 'localaccessortosharedmemory' on module '/tmp/zfp-4c499c.bc'.
```

On the SPIR-V back-end (`spir64_x86_64`), the use of a right funnel shifter:
```c++
inline uint32_t funnelshift_r(uint32_t lo, uint32_t hi, uint32_t shift) {
        if (shift == 0) return lo; // To avoid shifting by 32
        return (lo >> shift % 31) | (hi << (32 - (shift % 31)));
}
```

Results now in the following error:
```
InvalidFunctionCall: Unexpected llvm intrinsic:
 llvm.fshr.i32
```
Replacing the shifter implementation by `return 0` allows the code to compile on the spir-v back-end, and without any of the previously mentioned errors. But the behaviour is obviously wrong.

Everything compiles fine with older versions such as 8b56cbb1b8c688f88303c04435772d8269175e63 on all the targets.

** Reproducer **
I wasn't able to write a reproducer. I'm compiling with `-fsycl-targets=nvptx64-nvidia-cuda -Xsycl-target-backend=nvptx64-nvidia-cuda --cuda-gpu-arch=sm_75`. I can link the source code with build instructions if needed.

**Environment:**
- OS: Linux RHEL 8.4
- Target device and vendor: Intel CPU and Nvidia CUDA
- DPC++ version: 69e78f8b219dd4df37d716600095966b1785ef4f

### PR DESCRIPTION
**Pull request by AidanBeltonS**
When using `sycl-post-link` llvm.used should be removed. Otherwise it can cause a crash further on. 
This patch checks to see if llvm.used is removed and if it is prevents the old code from being reused in the table.

This fixes #4294. 
See issue for more details on problem.

### CODE REVIEW

**Review by mlychkov — DISMISSED** [review]
LGTM

**Comment by mlychkov** [comment]
@AidanBeltonS Could you please add a test for this fix?

**Comment by AidanBeltonS** [comment]
> @AidanBeltonS Could you please add a test for this fix?
Yes, ill work on adding one to test the desired behaviour.

File: llvm/tools/sycl-post-link/sycl-post-link.cpp [hunk 1]
```diff
@@ -988,15 +991,17 @@ int main(int argc, char **argv) {
   // and these declarations cause an assertion in llvm-spirv. To workaround this
   // issue remove "llvm.used" from the input module before performing any other
   // actions.
+  bool RemovedLLVMUsed = false;
   if (GlobalVariable *GV = MPtr->getGlobalVariable("llvm.used")) {
     assert(GV->user_empty() && "unexpected llvm.used users");
     GV->eraseFromParent();
+    RemovedLLVMUsed = true;
   }
```
Comment (mlychkov) [inline llvm/tools/sycl-post-link/sycl-post-link.cpp:999]: @sndmitriev May we move this code at the beginning of processOneModule? It wouldn't require to pass RemovedLLVMUsed down to that function.

File: clang/test/CodeGenSYCL/sycl-post-link-used-attr.cpp [hunk 2]
```diff
@@ -0,0 +1,31 @@
+// RUN: %clang_cc1 -disable-llvm-passes %s -emit-llvm -o - | sycl-post-link -split=auto -ir-output-only -o %t.out_ir_only.bc
```
Comment (bader) [inline clang/test/CodeGenSYCL/sycl-post-link-used-attr.cpp:1]: @AidanBeltonS, `sycl-post-link` tool is an LLVM tool, so the test should be llvm/test/tools/sycl-post-link/ and input file should be LLVM IR. It should be easy to create from the clang output. Please, take a look at other tests 
from llvm/test/tools/sycl-post-link/.

Comment (AlexeySachkov) [reply clang/test/CodeGenSYCL/sycl-post-link-used-attr.cpp:1]: Using `sed` is also not a good idea, I think, because it might not be available in all environments we test (like Windows, for example)

Comment (AidanBeltonS) [reply clang/test/CodeGenSYCL/sycl-post-link-used-attr.cpp:1]: Okay, that makes sense. There is an already existing test `erase_used.ll` in llvm/tools/sycl-post-link/ which performs a similar task. Is there a preference for adding a new test or extending an existing one?

Comment (bader) [reply clang/test/CodeGenSYCL/sycl-post-link-used-attr.cpp:1]: Extending `erase_used.ll` sounds like a good option to me.

File: llvm/tools/sycl-post-link/sycl-post-link.cpp (hunk 1 above)
Comment (mlychkov) [reply llvm/tools/sycl-post-link/sycl-post-link.cpp:999]: I think that lines 994-999 should be moved into processOneModule function.

Comment (AidanBeltonS) [reply llvm/tools/sycl-post-link/sycl-post-link.cpp:999]: I agree, it makes more sense as RemovedLLVMUsed does not have to be passed. I'll make the change.

File: llvm/tools/sycl-post-link/sycl-post-link.cpp [hunk 3]
```diff
@@ -714,6 +714,22 @@ static TableFiles processOneModule(std::unique_ptr<Module> M, bool IsEsimd,
...
+
+  // After linking device bitcode "llvm.used" holds references to the kernels
+  // that are defined in the device image. But after splitting device image into
+  // separate kernels we may end up with having references to kernel declaration
+  // originating from "llvm.used" in the IR that is passed to llvm-spirv tool,
+  // and these declarations cause an assertion in llvm-spirv. To workaround this
+  // issue remove "llvm.used" from the input module before performing any other
+  // actions.
+  bool IsLLVMUsedRemoved = false;
+  if (GlobalVariable *GV = MPtr->getGlobalVariable("llvm.used")) {
```
Comment (mlychkov) [inline llvm/tools/sycl-post-link/sycl-post-link.cpp:727]:
```suggestion
  // After linking device bitcode "llvm.used" holds references to the kernels
  // that are defined in the device image. But after splitting device image into
  // separate kernels we may end up with having references to kernel declaration
  // originating from "llvm.used" in the IR that is passed to llvm-spirv tool,
  // and these declarations cause an assertion in llvm-spirv. To workaround this
  // issue remove "llvm.used" from the input module before performing any other
  // actions.
  bool IsLLVMUsedRemoved = false;
  if (GlobalVariable *GV = M->getGlobalVariable("llvm.used")) {
```

**Review by bader — APPROVED** [review]

**Review by mlychkov — APPROVED** [review]
