### PR TITLE
[SYCL][CUDA] Add default to image format switch

### LINKED ISSUE #3550: [CUDA] Build error in imageElementByteSize
**Describe the bug**
Trying to build the CUDA backend fails with the following error:
```
/home/sjpennyc/llvm/sycl/plugins/cuda/pi_cuda.cpp: In function ‘size_t imageElementByteSize(CUDA_ARRAY_DESCRIPTOR)’:
/home/sjpennyc/llvm/sycl/plugins/cuda/pi_cuda.cpp:3824:10: error: enumeration value ‘CU_AD_FORMAT_NV12’ not handled in switch [-Werror=switch]
   switch (array_desc.Format) {
          ^
At global scope:
cc1plus: error: unrecognized command line option ‘-Wno-covered-switch-default’ [-Werror]
cc1plus: all warnings being treated as errors
```

I've added a `default` to the switch statement locally to work around this, but the error about `-Wno-covered-switch-default` suggests to me that this is a violation of some style guide and some other fix is expected.

**To Reproduce**
Build with:
```
python3 ../buildbot/configure.py --cuda -t Release
ninja
```

**Environment:**

- OS: Ubuntu 18.04
- C/CXX Compiler: GNU 7.5.0
- CUDA Version: 11.0

### PR DESCRIPTION
**Pull request by Pennycook**
Enables imageElementByteSize to compile when there are values of the
CUDA_ARRAY_DESCRIPTOR enum not explicitly covered by the switch statement,
such as when compiling with CUDA 11 (which adds CU_AD_FORMAT_NV12).

Closes #3550.

Signed-off-by: John Pennycook <john.pennycook@intel.com>

### CODE REVIEW

**Comment by steffenlarsen** [comment]
LGTM. Thank you for fixing this. CUDA 11 users rejoice!

File: sycl/plugins/cuda/pi_cuda.cpp [hunk 1]
```diff
@@ -3833,9 +3833,10 @@ static size_t imageElementByteSize(CUDA_ARRAY_DESCRIPTOR array_desc) {
   case CU_AD_FORMAT_SIGNED_INT32:
   case CU_AD_FORMAT_FLOAT:
     return 4;
+  default:
```
Comment (bader) [inline sycl/plugins/cuda/pi_cuda.cpp:3836]: I expect this to emit a warning with CUDA 10.2. :)
Probably the version which can be compiled with both SDKs should process CUDA 11 specific enum values under check `CUDA_VERSION` macro.

**Review by smaslov-intel — APPROVED** [review]

File: sycl/plugins/cuda/pi_cuda.cpp (hunk 1 above)
Comment (steffenlarsen) [reply sycl/plugins/cuda/pi_cuda.cpp:3836]: I agree. When support for the new enum is added, it should be under the constraint `CUDA_VERSION >= 11000`, but until that is implemented I think this is the best solution.

As for the warning, I suppose the `default` case could be wrapped in the `CUDA_VERSION >= 11000` constraint until the new macro is implemented. I think my primary concern is that once the new enum value is implemented (and assuming this does cause a warning), then we either have to remove the `default` case or give it a new constraint if we want to avoid the warning reappearing. If we remove it then we might end up in the same situation in the future. If we update the constraint to a higher (yet unreleased CUDA version), this warning may reappear once such a version is released, assuming it doesn't add a new enum value to `CUDA_ARRAY_DESCRIPTOR `. I can't think of a stable solution to this off the top of my head.

Comment (bader) [reply sycl/plugins/cuda/pi_cuda.cpp:3836]: Let's merge this version then.

FYI: there are no warnings in CI build with CUDA 10.1 due to `-Wno-covered-switch-default` flag - https://github.com/intel/llvm/blob/sycl/sycl/plugins/CMakeLists.txt#L4.
