### PR TITLE
[SYCL] Improve is_compatible

### LINKED ISSUE #7561: sycl::is_compatible is currently not very useful
**Describe the bug**

The spec is somewhat vague about the behavior of `is_compatible` :

> A kernel that is defined in the application is compatible with a device unless:
> • It uses optional features which are not supported on the device, as described in Section 5.7; or
> • It is decorated with a [[sycl::device_has()]] C++ attribute that lists an aspect that is not supported by
> the device, as described in Section 5.8.1.

The current implementation seems to fulfill these requirements, so it is not technically broken.

However, it does not handle many cases related to whether the device was targeted during compilation. One would expect that `is_compatible` returning `true` would mean that the kernel can be run on the device. This is not the case.

E.g., when targeting SPIR-V, the function falsely reports OpenCL AMD device as compatible (an exception is thrown when trying to launch the kernel) and throws an exception when called for HIP and CUDA devices (one would expect it to return `false`):

```console
$ clang++ -fsycl -fsycl-targets=spir64 test.cpp -o test
$ ONEAPI_DEVICE_SELECTOR=level_zero:gpu ./test # Works OK!
Checking Intel(R) UHD Graphics 770 [0x4680]
Device is compatible
$ ONEAPI_DEVICE_SELECTOR=opencl:gpu ./test # AMD device reported as compatible, while it is not
Checking Intel(R) UHD Graphics 770 [0x4680]
Device is compatible
Checking gfx1034
Device is compatible
terminate called after throwing an instance of 'sycl::_V1::runtime_error'
  what():  Native API failed. Native API returns: -59 (PI_ERROR_INVALID_OPERATION) -59 (PI_ERROR_INVALID_OPERATION)
Aborted (core dumped)
$ ONEAPI_DEVICE_SELECTOR=hip:gpu ./test # Now is_compatible itself throws instead of returning false
Checking AMD Radeon RX 6400
terminate called after throwing an instance of 'sycl::_V1::runtime_error'
  what():  Native API failed. Native API returns: -42 (PI_ERROR_INVALID_BINARY) -42 (PI_ERROR_INVALID_BINARY)
Aborted (core dumped)
```

If we target NVPTX backed with unsupported `--offload-arch`, the kernel is anyway reported as compatible, while it cannot be launched:

```console
$ clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda -Xsycl-target-backend --offload-arch=sm_90 test.cpp -o test
$ ONEAPI_DEVICE_SELECTOR=level_zero:gpu ./test # Throws again
Checking Intel(R) UHD Graphics 770 [0x4680]
terminate called after throwing an instance of 'sycl::_V1::runtime_error'
  what():  Native API failed. Native API returns: -42 (PI_ERROR_INVALID_BINARY) -42 (PI_ERROR_INVALID_BINARY)
Aborted (core dumped)
$ ONEAPI_DEVICE_SELECTOR=cuda:gpu ./test # I have sm_86 device, which is not compatible, yet the function reports that it is:
Checking NVIDIA GeForce RTX 3060
Device is compatible

PI CUDA ERROR:
        Value:           209
        Name:            CUDA_ERROR_NO_BINARY_FOR_GPU
        Description:     no kernel image is available for execution on the device
        Function:        build_program
        Source Location: /home/aland/intel-sycl/llvm/sycl/plugins/cuda/pi_cuda.cpp:733


PI CUDA ERROR:
        Value:           400
        Name:            CUDA_ERROR_INVALID_HANDLE
        Description:     invalid resource handle
        Function:        cuda_piProgramRelease
        Source Location: /home/aland/intel-sycl/llvm/sycl/plugins/cuda/pi_cuda.cpp:3609

terminate called after throwing an instance of 'sycl::_V1::compile_program_error'
  what():  The program was built for 1 devices
Build program log for 'NVIDIA GeForce RTX 3060':
 -999 (Unknown PI error)
Aborted (core dumped)
```

**To Reproduce**

```cpp
#include <iostream>
#include <CL/sycl.hpp>

class Kernel;

int main()
{
    for (const auto& dev : sycl::device::get_devices())
    {
        std::cout << "Checking " << dev.get_info<sycl::info::device::name>() << std::endl;
        bool deviceOk = sycl::is_compatible<Kernel>(dev);
        std::cout << "Device is " << (deviceOk ? "compatible" : "incompatible") << std::endl;
        if (deviceOk)
        {
            sycl::queue q{ dev };
            q.submit([&](sycl::handler& cgh) {
                 cgh.parallel_for<Kernel>(sycl::range<1>{ 1 },
                                          [=](sycl::id<1> threadId) { int x = threadId[0]; });
             }).wait_and_throw();
        }
    }
    return 0;
}
```

**Environment (please complete the following information):**

- OS: Ubuntu 20.04
- Target device and vendor: Intel, NVIDIA, AMD GPU
- DPC++ version: clang version 16.0.0 (https://github.com/intel/llvm 67f6bba2537dbacf91f023caf830d9dbb7536f33)
- Dependencies version: Intel compute runtime 22.39.24347, CUDA 11.8, ROCm 5.3.3

### PR DESCRIPTION
**Pull request by KornevNikita**
Modify `is_compatible` to check if specific target is defined with `-fsycl-targets` and change the result. Previously there was a situation when kernel is compatible with the device by aspects, but actually it fails to run on this device as it was compiled for another target device.

Related spec change: https://github.com/KhronosGroup/SYCL-Docs/pull/381

Resolves #7561

### CODE REVIEW

File: sycl/test-e2e/OptionalKernelFeatures/is_compatible/is_compatible_spir64_x86_64.cpp [hunk 1]
```diff
@@ -0,0 +1,6 @@
+// REQUIRES: gpu, level_zero, opencl
```
Comment (dm-vodopyanov) [inline sycl/test-e2e/OptionalKernelFeatures/is_compatible/is_compatible_spir64_x86_64.cpp:1]: Can you please also add tests for CUDA and HIP?

File: sycl/source/kernel_bundle.cpp [hunk 2]
```diff
@@ -290,12 +290,52 @@ std::vector<kernel_id> get_kernel_ids() {
...
+    } else if (strcmp(Target, __SYCL_PI_DEVICE_BINARY_TARGET_NVPTX64) == 0) {
+      return BE == sycl::backend::ext_oneapi_cuda;
+    } else if (strcmp(Target, __SYCL_PI_DEVICE_BINARY_TARGET_AMDGCN) == 0) {
+      return BE == sycl::backend::ext_oneapi_hip;
+    }
+
+    return false;
+  };
+
+  // One kernel may be contained in several binary images depending on the
```
Comment (dm-vodopyanov) [inline sycl/source/kernel_bundle.cpp:322]: Can you please add a test for that?

File: sycl/source/kernel_bundle.cpp [hunk 3]
```diff
@@ -290,12 +290,52 @@ std::vector<kernel_id> get_kernel_ids() {
...
-                     });
+  if (KernelIDs.empty())
+    return false;
+  // TODO: also need to check architectures matching
+  auto doesImageTargetMatchDevice = [](const device &Dev,
+                                       const detail::RTDeviceBinaryImage &Img) {
+    const char *Target = Img.getRawData().DeviceTargetSpec;
+    auto BE = Dev.get_backend();
+    if (strcmp(Target, __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64) == 0) {
+      return (BE == sycl::backend::opencl ||
```
Comment (dm-vodopyanov) [inline sycl/source/kernel_bundle.cpp:301]: There is also `backend::ext_intel_esimd_emulator`, should it be also supported by `is_compatible`?

File: sycl/test-e2e/OptionalKernelFeatures/is_compatible/is_compatible_spir64_x86_64.cpp (hunk 1 above)
Comment (KornevNikita) [reply sycl/test-e2e/OptionalKernelFeatures/is_compatible/is_compatible_spir64_x86_64.cpp]: [44d5c89](https://github.com/intel/llvm/pull/9769/commits/44d5c89980e3879df1784c952e554b61ff8f09a1)

File: sycl/source/kernel_bundle.cpp (hunk 3 above)
Comment (KornevNikita) [reply sycl/source/kernel_bundle.cpp:301]: 7cce706

File: sycl/source/kernel_bundle.cpp (hunk 2 above)
Comment (KornevNikita) [reply sycl/source/kernel_bundle.cpp:323]: [1bafaa7](https://github.com/intel/llvm/pull/9769/commits/1bafaa7139c797f9dd1cb0c42bad2630964be6f8)

File: sycl/source/kernel_bundle.cpp (hunk 3 above)
Comment (dm-vodopyanov) [reply sycl/source/kernel_bundle.cpp:301]: Can you please add a test for that too?

File: sycl/test-e2e/OptionalKernelFeatures/is_compatible/is_compatible_spir64_x86_64.cpp [hunk 4]
```diff
@@ -0,0 +1,7 @@
+// REQUIRES: level_zero
```
Comment (dm-vodopyanov) [inline sycl/test-e2e/OptionalKernelFeatures/is_compatible/is_compatible_spir64_x86_64.cpp:1]:
```suggestion
// REQUIRES: opencl-aot, cpu
```
?

File: sycl/test-e2e/OptionalKernelFeatures/is_compatible/is_compatible_spir64_fpga.cpp [hunk 5]
```diff
@@ -0,0 +1,7 @@
+// REQUIRES: gpu, accelerator
```
Comment (dm-vodopyanov) [inline sycl/test-e2e/OptionalKernelFeatures/is_compatible/is_compatible_spir64_fpga.cpp:1]:
```suggestion
// REQUIRES: accelerator
```
?

File: sycl/source/kernel_bundle.cpp (hunk 3 above)
Comment (KornevNikita) [reply sycl/source/kernel_bundle.cpp:301]: b4cb2dd

File: sycl/test-e2e/OptionalKernelFeatures/is_compatible/is_compatible_spir64_x86_64.cpp (hunk 4 above)
Comment (KornevNikita) [reply sycl/test-e2e/OptionalKernelFeatures/is_compatible/is_compatible_spir64_x86_64.cpp]: b4cb2dd

File: sycl/test-e2e/OptionalKernelFeatures/is_compatible/is_compatible_spir64_fpga.cpp (hunk 5 above)
Comment (KornevNikita) [reply sycl/test-e2e/OptionalKernelFeatures/is_compatible/is_compatible_spir64_fpga.cpp]: b4cb2dd

File: sycl/source/kernel_bundle.cpp (hunk 3 above)
Comment (KornevNikita) [reply sycl/source/kernel_bundle.cpp:309]: Test for esimd: [187bf48](https://github.com/intel/llvm/pull/9769/commits/187bf48c79615cd1d6ffa53e382021cc32a391b1)

File: sycl/source/kernel_bundle.cpp [hunk 6]
```diff
@@ -290,12 +290,53 @@ std::vector<kernel_id> get_kernel_ids() {
...
+              BE == sycl::backend::ext_oneapi_level_zero ||
+              BE == sycl::backend::ext_intel_esimd_emulator);
+    } else if (strcmp(Target, __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64_X86_64) ==
+               0) {
+      return Dev.is_cpu();
+    } else if (strcmp(Target, __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64_GEN) ==
+               0) {
+      return Dev.is_gpu() && (BE == sycl::backend::opencl ||
```
[the remark this answers is not in the document]
Comment (KornevNikita) [reply sycl/source/kernel_bundle.cpp:316]: I guess no. First of all - most likely esimd kernels have spir64 target. The second thing - there is a restriction for esimd_emulator to execute non-esimd kernels. So, I assume that we only need here to check that if we have esimd_emulator device - then we have a esimd kernel.

File: sycl/source/kernel_bundle.cpp [hunk 7]
```diff
@@ -290,12 +291,59 @@ std::vector<kernel_id> get_kernel_ids() {
...
+  if (KernelIDs.empty())
+    return false;
+  // TODO: also need to check that the architecture specified by the
+  // "-fsycl-targets" flag matches the device when we are able to get the
+  // device's arch.
+  auto doesImageTargetMatchDevice = [](const device &Dev,
+                                       const detail::RTDeviceBinaryImage &Img) {
+    const char *Target = Img.getRawData().DeviceTargetSpec;
+    auto BE = Dev.get_backend();
+    // ESIMD emulator is only compatible with esimd kernels.
```
Comment (dm-vodopyanov) [inline sycl/source/kernel_bundle.cpp:303]:
```suggestion
    // ESIMD emulator backend is only compatible with esimd kernels.
```

File: sycl/test-e2e/OptionalKernelFeatures/is_compatible/is_compatible_esimd_emulator.cpp [hunk 8]
```diff
@@ -0,0 +1,41 @@
...
+                                      simd<float, VL> va(A + offset);
+                                      simd<float, VL> vb(B + offset);
+                                      simd<float, VL> vc = va + vb;
+                                      vc.copy_to(C + offset);
+                                    });
+     }).wait_and_throw();
+    return 0;
+  }
+  return 1;
+}
```
Comment (dm-vodopyanov) [inline sycl/test-e2e/OptionalKernelFeatures/is_compatible/is_compatible_esimd_emulator.cpp:41]: nit: missing empty line

**Review by dm-vodopyanov — APPROVED** [review]

File: sycl/source/kernel_bundle.cpp [hunk 9]
```diff
@@ -290,12 +291,59 @@ std::vector<kernel_id> get_kernel_ids() {
...
 
 bool is_compatible(const std::vector<kernel_id> &KernelIDs, const device &Dev) {
-  std::set<detail::RTDeviceBinaryImage *> BinImages =
-      detail::ProgramManager::getInstance().getRawDeviceImages(KernelIDs);
-  return std::all_of(BinImages.begin(), BinImages.end(),
-                     [&Dev](const detail::RTDeviceBinaryImage *Img) {
-                       return doesDevSupportDeviceRequirements(Dev, *Img);
-                     });
+  if (KernelIDs.empty())
+    return false;
```
Comment (jzc) [inline sycl/source/kernel_bundle.cpp:295]: Why should `is_compatible` return false if `KernelIDs` is empty?

Comment (KornevNikita) [reply sycl/source/kernel_bundle.cpp:295]: Spec says: `Returns: true if all of the kernels identified by kernelIds are compatible with the device dev.` I guess for this case since we don't have kernels at all, we shouldn't return true here. Do you have another opinion?

Comment (al42and) [reply sycl/source/kernel_bundle.cpp:295]: How do we handle empty list of kernels in `has_kernel_bundle`?  `std::all_of` returns `true` for an empty array, so, from this point, returning `true` for empty list of kernels would make sense.

The standard does not explicitly cover this case, and SYCL CTS [explicitly skips the cases of empty vectors](https://github.com/KhronosGroup/SYCL-CTS/blob/e9ffbe9a2cad6b8a31c5bab58d05d836a2338df9/tests/kernel_bundle/sycl_is_compatible.cpp). But their use of `CHECK(sycl::is_compatible(builtinKernelIds, device))` suggests that returning `true` for an empty array would be more consistent with how this function is expected to be used.

Comment (KornevNikita) [reply sycl/source/kernel_bundle.cpp:295]: Okay, I clarified this point, it should return true - https://github.com/intel/llvm/pull/9903
