### PR TITLE
[SYCL][E2E] Re-enable tests hanging on Windows BMG

### LINKED ISSUE #18067: [E2E] `Adapters/level_zero_eager_init.cpp` induces other tests to hang on Windows BMG with prebuilt E2E binaries
### Describe the bug

Running `Adapters/level_zero_eager_init.cpp` on Battlemage on windows with prebuilt E2E binaries flakily XPASSes, or induces other tests to hang. Verified on CI.

Runs prior to changing markup for `Adapters/level_zero_eager_init.cpp` could hang:
- https://github.com/intel/llvm/actions/runs/14476883669/job/40606429193

The E2E tests do not hang here, but `Adapters/level_zero_eager_init.cpp` reports as XPASS:
- https://github.com/intel/llvm/actions/runs/14480096620/job/40616327172

After removing the XFAIL from `Adapters/level_zero_eager_init.cpp`, a test hangs, and after disabling the hanging test a different test hangs:
- https://github.com/intel/llvm/actions/runs/14481582243/job/40620609360
- https://github.com/intel/llvm/actions/runs/14483077653/job/40624380817

After disabling the `Adapters/level_zero_eager_init.cpp` (instead of XFAILing) E2E tests pass without hanging:
- https://github.com/intel/llvm/actions/runs/14497224154/attempts/1
- https://github.com/intel/llvm/actions/runs/14497224154/attempts/2
- https://github.com/intel/llvm/actions/runs/14497224154/attempts/3

### Environment

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ayylol**
Fixes #18067 and #17582 

These were fixed with the Windows driver being updated.

### CODE REVIEW

File: sycl/test-e2e/Adapters/level_zero/eager_init.cpp [hunk 1]
```diff
@@ -3,9 +3,6 @@
 // UNSUPPORTED-INTENDED: ze_debug UR emits summary of leaks that contains
 // function names that we match in the test.
 
-// UNSUPPORTED: windows && arch-intel_gpu_bmg_g21
```
Comment (sarnex) [inline sycl/test-e2e/Adapters/level_zero/eager_init.cpp:6]: When this is merged lets make sure to close/update all the linked GH issues

**Review by sarnex — APPROVED** [review]

**Review by igchor — APPROVED** [review]

**Comment by ayylol** [comment]
@intel/llvm-reviewers-runtime friendly ping

**Review by aelovikov-intel — APPROVED** [review]
