### PR TITLE
[UR] fix: synchronize resubmission of the same command buffer

### LINKED ISSUE #18610: [UR][L0 v2] `urEnqueueCommandBufferExpTest.SerializeAcrossQueues` flaky on PVC
### Describe the bug

Unrelated PRs have seen fails with the UR CTS test  `urEnqueueCommandBufferExpTest.SerializeAcrossQueues` on the L0 V2 adapter on PVC:

* https://github.com/intel/llvm/actions/runs/15167170761/job/42648828577?pr=18573#step:12:7806
* https://github.com/intel/llvm/actions/runs/15166894381/job/42647791106?pr=18423#step:12:7811
```
15: [ RUN      ] urEnqueueCommandBufferExpTest.SerializeOutofOrderQueue/UR_BACKEND_LEVEL_ZERO__Intel_R__oneAPI_Unified_Runtime_over_Level_Zero_V2__Intel_R__Data_Center_GPU_Max_1100_ID0ID____________________
15: /__w/llvm/llvm/unified-runtime/test/conformance/exp_command_buffer/enqueue.cpp:132: Failure
15: Expected equality of these values:
15:   reference
15:     Which is: 2
15:   Output[i]
15:     Which is: 1
15: [  FAILED  ] urEnqueueCommandBufferExpTest.SerializeOutofOrderQueue/UR_BACKEND_LEVEL_ZERO__Intel_R__oneAPI_Unified_Runtime_over_Level_Zero_V2__Intel_R__Data_Center_GPU_Max_1100_ID0ID____________________, where GetParam() = 24-byte object <40-1D 30-0C E5-5C 00-00 20-D9 1A-0C E5-5C 00-00 B0-56 65-0A E5-5C 00-00> (0 ms)
```

Test disabled for v2 adapter in https://github.com/intel/llvm/pull/18611 

FYI @pbalcer @Xewar313

### PR DESCRIPTION
**Pull request by EuphoricThinking**
Fixes #18610

### CODE REVIEW

File: unified-runtime/source/adapters/level_zero/v2/command_list_manager.cpp [hunk 1]
```diff
@@ -158,19 +158,14 @@ ur_result_t ur_command_list_manager::appendRegionCopyUnlocked(
 }
 
 wait_list_view ur_command_list_manager::getWaitListView(
-    const ur_event_handle_t *phWaitEvents, uint32_t numWaitEvents,
-    ur_event_handle_t additionalWaitEvent) {
+    const ur_event_handle_t *phWaitEvents, uint32_t numWaitEvents) {
```
Comment (pbalcer) [inline unified-runtime/source/adapters/level_zero/v2/command_list_manager.cpp:161]: @staniewzki is using this API in https://github.com/intel/llvm/pull/18179/files#diff-57b5ceadf73f501ea8d07f9837583b61b45ca22129f3aacdeda1fb0b582a9990R735-R736.

File: unified-runtime/test/conformance/exp_command_buffer/enqueue.cpp [hunk 2]
```diff
@@ -42,6 +42,22 @@ struct urEnqueueCommandBufferExpTest
...
+    const int num_copy_buffers = 10;
+    const int buffer_size = 512;
+    int* dst_buffers[num_copy_buffers];
+    int* src_buffers[num_copy_buffers];
+
+    std::vector<int> temp_val(buffer_size, 3);
+
+    for (int i = 0; i < num_copy_buffers; i++) {
+      ASSERT_SUCCESS(urUSMDeviceAlloc(context, device, nullptr, nullptr, buffer_size * sizeof(int), (void**) &(dst_buffers[i])));
+      ASSERT_SUCCESS(urUSMDeviceAlloc(context, device, nullptr, nullptr, buffer_size * sizeof(int), (void**) &(src_buffers[i])));
```
Comment (EwanC) [inline unified-runtime/test/conformance/exp_command_buffer/enqueue.cpp:55]: These allocations are being leaked. The `dst_buffers`/`src_buffers` arrays should be a class members, and then the elements feed in `TearDown` with `urUSMFree`

File: unified-runtime/test/conformance/exp_command_buffer/enqueue.cpp [hunk 3]
```diff
@@ -132,3 +154,25 @@ TEST_P(urEnqueueCommandBufferExpTest, SerializeOutofOrderQueue) {
     ASSERT_EQ(reference, Output[i]);
   }
 }
+
+TEST_P(urEnqueueCommandBufferExpTest, SerializeInOrderQueue) {
```
Comment (pbalcer) [inline unified-runtime/test/conformance/exp_command_buffer/enqueue.cpp:158]: this test is nearly identical to `SerializeOutofOrderQueue`. Parameters are just different. You could use `UUR_DEVICE_TEST_SUITE_WITH_PARAM` or just create a function with the body of the test. Whatever is simpler (though using the macro is probably more idiomatic).

File: unified-runtime/test/conformance/exp_command_buffer/fixtures.h [hunk 4]
```diff
@@ -97,8 +97,9 @@ struct urCommandBufferExpExecutionTest : uur::urKernelExecutionTest {
 
     UUR_RETURN_ON_FATAL_FAILURE(checkCommandBufferSupport(device));
 
+    // in-order command buffer
     ur_exp_command_buffer_desc_t desc{UR_STRUCTURE_TYPE_EXP_COMMAND_BUFFER_DESC,
-                                      nullptr, false, false, false};
+                                      nullptr, false, true /* WAS: false */, false};
```
[the remark this answers is not in the document]
Comment (EuphoricThinking) [reply unified-runtime/test/conformance/exp_command_buffer/fixtures.h:102]: In order to extend the time of the buffer execution, but as @pbalcer mentioned, I'll revert this to out-of-order

File: unified-runtime/test/conformance/exp_command_buffer/enqueue.cpp [hunk 5]
```diff
@@ -53,53 +63,108 @@ struct urEnqueueCommandBufferExpTest
...
+      }
+    }
+
+    UUR_RETURN_ON_FATAL_FAILURE(
+        urCommandBufferExpExecutionTestWithParam::TearDown());
   }
 
-  ur_queue_handle_t in_order_queue = nullptr;
-  ur_queue_handle_t out_of_order_queue = nullptr;
+  ur_queue_handle_t in_or_out_of_order_queue = nullptr;
```
Comment (pbalcer) [inline unified-runtime/test/conformance/exp_command_buffer/enqueue.cpp:101]: just call it queue.

Comment (igchor) [reply unified-runtime/test/conformance/exp_command_buffer/enqueue.cpp:101]: Can't we use the one from the parent class then? I think we can just modify queue_properties BEFORE calling parent SetUp (`UUR_RETURN_ON_FATAL_FAILURE(
        urCommandBufferExpExecutionTestWithParam::SetUp());`) to make it in-order or out-of-order

File: unified-runtime/test/conformance/exp_command_buffer/enqueue.cpp [hunk 6]
```diff
@@ -53,53 +63,102 @@ struct urEnqueueCommandBufferExpTest
...
+  ur_queue_flags_t queue_type;
```
[the remark this answers is not in the document]
Comment (EuphoricThinking) [reply unified-runtime/test/conformance/exp_command_buffer/enqueue.cpp]: No, once upon a time I've thought this looks better, but these times are gone.

File: unified-runtime/test/conformance/exp_command_buffer/enqueue.cpp (hunk 3 above)
Comment (EuphoricThinking) [reply unified-runtime/test/conformance/exp_command_buffer/enqueue.cpp]: I've used the macro and introduced a new fixture for parametrized tests.

**Review by EwanC — APPROVED** [review]
LGTM

**Review by pbalcer — APPROVED** [review]

File: unified-runtime/source/adapters/level_zero/v2/queue_immediate_in_order.cpp [hunk 7]
```diff
@@ -1025,6 +1025,10 @@ ur_result_t ur_queue_immediate_in_order_t::enqueueCommandBufferExp(
   ur_event_handle_t executionEvent =
       hCommandBuffer->getExecutionEventUnlocked();
 
+  if (executionEvent != nullptr) {
+    ZE2UR_CALL(zeEventHostSynchronize, (executionEvent->getZeEvent(), UINT64_MAX));
+  }
+
   UR_CALL(enqueueGenericCommandListsExp(
       1, &commandBufferCommandList, phEvent, numEventsInWaitList,
       phEventWaitList, UR_COMMAND_ENQUEUE_COMMAND_BUFFER_EXP, executionEvent));
```
[the remark this answers is not in the document]
Comment (pbalcer) [reply unified-runtime/source/adapters/level_zero/v2/queue_immediate_in_order.cpp:1035]: See, that was my initial suggestion (and that's how @EuphoricThinking did it at first). However, this parameter is now being used in async alloc, https://github.com/intel/llvm/pull/18179, so we can't get rid of it.

[the remark this answers is not in the document]
Comment (EuphoricThinking) [reply unified-runtime/source/adapters/level_zero/v2/queue_immediate_in_order.cpp]: I've changed to `nullptr` as @pbalcer has suggested.

File: unified-runtime/test/conformance/exp_command_buffer/enqueue.cpp (hunk 5 above)
Comment (EuphoricThinking) [reply unified-runtime/test/conformance/exp_command_buffer/enqueue.cpp:99]: SerializeAcrossQueues needs two queues, for now I'd leave it with the creation of an additional queue (as it is implemented at this moment).

**Review by pbalcer — APPROVED** [review]

**Comment by pbalcer** [comment]
@intel/llvm-gatekeepers please merge
