### PR TITLE
[SYCL] Change `vec::operator!` to match SYCL spec

### LINKED ISSUE #11659: `vec::operator!` has wrong return type
**Describe the bug**

According to [4.14.2.1. Vec interface](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_vec_interface), `vec::operator!` is defined as:

> `vec<RET, NumElements> operator!(const vec& v)`
> 
> Construct a new instance of the SYCL `vec` class template with the same template parameters as v vec with each element of the new SYCL `vec` instance the result of an element-wise `OP` logical operation on each element of `v vec`. Each element of the SYCL `vec` that is returned must be `-1` if the operation results in `true` and `0` if the operation results in `false` or this SYCL `vec` is a `NaN`.
>
> **The `DataT` template parameter of the constructed SYCL `vec`, `RET`, varies depending on the `DataT` template parameter of this SYCL `vec`. For a SYCL `vec` with `DataT` of type `int8_t` or `uint8_t` `RET` must be `int8_t`. For a SYCL `vec` with `DataT` of type `int16_t`, `uint16_t` or `half` `RET` must be `int16_t`. For a SYCL `vec` with `DataT` of type `int32_t`, `uint32_t` or `float` `RET` must be `int32_t`. For a SYCL `vec` with `DataT` of type `int64_t`, `uint64_t` or `double` `RET` must be `int64_t`.**

Apparently, we do not set `RET` correctly and simply re-using `DataT` from this SYCL `vec`.

**To Reproduce**

```c++
#include <sycl/sycl.hpp>

int main() {
  sycl::vec<float, 4> a(42);
  sycl::vec<unsigned long long, 4> b(24);
  sycl::vec<std::int32_t, 4> c = !a;
  sycl::vec<std::int64_t, 4> d = !b;

  return 0;
}
```

```
$ clang++ -fsycl  t.cpp
t.cpp:6:30: error: no viable conversion from 'EnableIfNotUsingArray<vec<float, 4>>' (aka 'sycl::vec<float, 4>') to
      'sycl::vec<std::int32_t, 4>' (aka 'vec<int, 4>')
    6 |   sycl::vec<std::int32_t, 4> c = !a;
      |                              ^   ~~
t.cpp:7:30: error: no viable conversion from 'EnableIfNotUsingArray<vec<unsigned long long, 4>>'
      (aka 'sycl::vec<unsigned long long, 4>') to 'sycl::vec<std::int64_t, 4>' (aka 'vec<long, 4>')
    7 |   sycl::vec<std::int64_t, 4> d = !b;
      |                              ^   ~~
```

### PR DESCRIPTION
**Pull request by 0x12CC**
Table 143 of the SYCL 2020 specification states that the return for the `!` operator can be a different vector type. This change implements the interface described in the specification. Fixes #11659.

### CODE REVIEW

File: sycl/test/basic_tests/types.cpp [hunk 1]
```diff
@@ -130,8 +142,21 @@ template <typename T> void checkVecUnaryOps(T &v) {
     std::cout << vec2string(g) << std::endl;
   }
 
-  T f = !v;
+  auto f = !v;
   std::cout << vec2string(f) << std::endl;
+
+  // Check operator! return type
+  checkVecNotReturnType<int8_t, int8_t>();
```
Comment (AlexeySachkov) [inline sycl/test/basic_tests/types.cpp:149]: We are not exactly allowed to do such API changes just yet and therefore the change should be hidden under our new `__INTEL_PREVIEW_BREAKING_CHANGES` macro.

For the implementation itself, that would be a no-op once #11697 is merged, because we will only have to update the new version of the interface. The test, however, will have to be conditionalized and run twice

File: sycl/include/sycl/types.hpp [hunk 2]
```diff
@@ -1191,32 +1203,45 @@ template <typename Type, int NumElements> class vec {
...
+                            vec<OpNotRet<T>, N>>
   operator!() const {
     vec Ret{};
     for (size_t I = 0; I < NumElements; ++I) {
       Ret.setValue(I, std::byte{!vec_data<DataT>::get(getValue(I))});
     }
+    return Ret.template as<vec<OpNotRet<T>, N>>();
+#if defined(__INTEL_PREVIEW_BREAKING_CHANGES)
+    return Ret.template as<vec<OpNotRet<T>, N>>();
+#else
```
Comment (steffenlarsen) [inline sycl/include/sycl/types.hpp:1215]: This looks odd. Is it supposed to have the return before the ifdef?

**Review by steffenlarsen — APPROVED** [review]
LGTM!
