### PR TITLE
fix Memory Export Extension UR API error list

### LINKED ISSUE #20462: [Coverity][UR] Confusing error codes definition of Memory Export Extension UR APIs
This was reported by intel/llvm Coverity scan available at https://scan.coverity.com/projects/intel-llvm?tab=overview

CIDs: `535434`, `535466` and `535401`

`exp-memory-export.yml` defines 3 API end points with the same pattern of error checking:

https://github.com/intel/llvm/blob/220a474528ac5ea817ab734e334fc2b9232350f2/unified-runtime/scripts/core/exp-memory-export.yml#L59-L62

https://github.com/intel/llvm/blob/220a474528ac5ea817ab734e334fc2b9232350f2/unified-runtime/scripts/core/exp-memory-export.yml#L94-L97

https://github.com/intel/llvm/blob/220a474528ac5ea817ab734e334fc2b9232350f2/unified-runtime/scripts/core/exp-memory-export.yml#L136-L139

This leads to the following error checking code being generated:

```
if (NULL == hContext)
  return UR_RESULT_ERROR_INVALID_NULL_HANDLE;
if (NULL == hDevice)
  return UR_RESULT_ERROR_INVALID_NULL_HANDLE;
if ((hDevice == nullptr) || (hContext == nullptr))
  return UR_RESULT_ERROR_INVALID_NULL_HANDLE;
```

Where the last `return` is logically dead code, because it is unreachable. The code isn't a problem by itself, but I think that it is still worth to address this, because it is not clear which exact error code a caller should expect from this API in case any of the handles are invalid.

Perhaps I misunderstand the definition of `X_RESULT_ERROR_INVALID_CONTEXT` and it should do a deeper check than just comparing a handle to `nulltpr`? BTW, why in the YAML file we have 3 distinct error codes (assuming that `ERROR_INVALID_CONTEXT` and `ERROR_INVALID_DEVICE` aren't aliases), while in the implementation we only ever emit `ERROR_INVALID_NULL_HANDLE`?

### PR DESCRIPTION
**Pull request by bratpiorka**
fix the list of returned error opcodes for the Memory Export Extension UR API

fixes #20462

### CODE REVIEW

File: unified-runtime/include/ur_api.h [hunk 1]
```diff
@@ -12661,11 +12660,10 @@ UR_APIEXPORT ur_result_t UR_APICALL urMemoryExportAllocExportableMemoryExp(
 ///     - ::UR_RESULT_ERROR_INVALID_NULL_HANDLE
 ///         + `NULL == hContext`
 ///         + `NULL == hDevice`
-///         + `(hDevice == nullptr) || (hContext == nullptr)`
+///     - ::UR_RESULT_ERROR_INVALID_NULL_POINTER
+///         + `NULL == pMem`
```
Comment (pbalcer) [inline unified-runtime/include/ur_api.h]:
```suggestion
///         + `pMem == nullptr`
```
