### PR TITLE
[SYCL] Adds support for atomic fence capabilities device queries

### LINKED ISSUE #8293: sycl::info::device:: atomic_fence_scope_capabilities and atomic_fence_order_capabilities are not implemented
In SYCL 2020 sycl::info::device::atomic_fence_scope_capabilities and sycl::info::device::atomic_fence_order_capabilities are introduced [4.6.4.2. Device information descriptors](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_device_information_descriptors) but not implemented.

**To Reproduce**

```
#include <sycl.hpp>

int main() {
  auto scope_capabilities = sycl::info::device::atomic_fence_scope_capabilities;
  auto order_capabilities = sycl::info::device::atomic_fence_order_capabilities;
}
```
To build:
`clang++ -fsycl ./sample_capabilities.cpp -o sample`

Output:
```
./sample_capabilities.cpp:4:49: error: no member named 'atomic_fence_scope_capabilities' in namespace 'sycl::info::device'
  auto scope_capabilities = sycl::info::device::atomic_fence_scope_capabilities;
                            ~~~~~~~~~~~~~~~~~~~~^
./sample_capabilities.cpp:5:49: error: no member named 'atomic_fence_order_capabilities' in namespace 'sycl::info::device'
  auto order_capabilities = sycl::info::device::atomic_fence_order_capabilities;
                            ~~~~~~~~~~~~~~~~~~~~^
2 errors generated.
```

**Environment (please complete the following information):**

- OS: Linux
- DPC++ version: `clang version 16.0.0 (/netbatch/donb2243735_00/runDir/jenkins-dir/workspace/Tools_SH/SYCLOS_Nightly/RHEL/llvm.src/clang 188ef654129ec5f8ceeba0fc242f8ae2fcba7530)`

### PR DESCRIPTION
**Pull request by maarquitos14**
Adds support to query devices for `atomic_fence_order_capabilities` and `atomic_fence_scope_capabilities`. The backends supported are OpenCL and Level Zero. For the rest of backends, it has been left unsupported.

Fixes #8293.

### CODE REVIEW

**Review by npmiller — APPROVED** [review]
PI CUDA and PI HIP changes LGTM

**Comment by maarquitos14** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1658

File: sycl/include/sycl/detail/pi.h [hunk 1]
```diff
@@ -611,13 +615,13 @@ using pi_queue_properties = pi_bitfield;
...
-constexpr pi_queue_properties PI_EXT_ONEAPI_QUEUE_FLAG_DISCARD_EVENTS = (1 << 4);
-constexpr pi_queue_properties PI_EXT_ONEAPI_QUEUE_FLAG_PRIORITY_LOW = (1 << 5);
-constexpr pi_queue_properties PI_EXT_ONEAPI_QUEUE_FLAG_PRIORITY_HIGH = (1 << 6);
+    constexpr pi_queue_properties PI_QUEUE_FLAG_OUT_OF_ORDER_EXEC_MODE_ENABLE = (1 << 0);
+    constexpr pi_queue_properties PI_QUEUE_FLAG_PROFILING_ENABLE = (1 << 1);
+    constexpr pi_queue_properties PI_QUEUE_FLAG_ON_DEVICE = (1 << 2);
+    constexpr pi_queue_properties PI_QUEUE_FLAG_ON_DEVICE_DEFAULT = (1 << 3);
+    constexpr pi_queue_properties PI_EXT_ONEAPI_QUEUE_FLAG_DISCARD_EVENTS = (1 << 4);
+    constexpr pi_queue_properties PI_EXT_ONEAPI_QUEUE_FLAG_PRIORITY_LOW = (1 << 5);
+    constexpr pi_queue_properties PI_EXT_ONEAPI_QUEUE_FLAG_PRIORITY_HIGH = (1 << 6);
```
[the remark this answers is not in the document]
Comment (maarquitos14) [reply sycl/include/sycl/detail/pi.h:624]: My local clang-format overreacted. I will revert the changes.

**Comment by maarquitos14** [comment]
Friendly ping @intel/dpcpp-esimd-reviewers @intel/llvm-reviewers-runtime @intel/dpcpp-l0-pi-reviewers

**Review by sarnex — APPROVED** [review]
esimd emulator lgtm

**Comment by maarquitos14** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1658

**Comment by maarquitos14** [comment]
@intel/llvm-reviewers-runtime assigned reviewer is on holiday, could you please take a look?

**Comment by maarquitos14** [comment]
Friendly ping @intel/dpcpp-l0-pi-reviewers.

File: sycl/include/sycl/detail/pi.h [hunk 2]
```diff
@@ -77,9 +77,11 @@
 // 12.22 Add piGetDeviceAndHostTimer to query device wall-clock timestamp
 // 12.23 Added new piextEnqueueDeviceGlobalVariableWrite and
 // piextEnqueueDeviceGlobalVariableRead functions.
+// 12.24 Added PI_DEVICE_INFO_ATOMIC_FENCE_ORDER_CAPABILITIES and
```
Comment (smaslov-intel) [inline sycl/include/sycl/detail/pi.h:80]: @kbenzie: please take this change to Unified Runtime

File: sycl/include/sycl/detail/pi.h [hunk 3]
```diff
@@ -313,6 +315,8 @@ typedef enum {
   PI_DEVICE_INFO_ATOMIC_64 = 0x10110,
   PI_DEVICE_INFO_ATOMIC_MEMORY_ORDER_CAPABILITIES = 0x10111,
   PI_DEVICE_INFO_ATOMIC_MEMORY_SCOPE_CAPABILITIES = 0x11000,
+  PI_DEVICE_INFO_ATOMIC_FENCE_ORDER_CAPABILITIES = 0x10114,
+  PI_DEVICE_INFO_ATOMIC_FENCE_SCOPE_CAPABILITIES = 0x10115,
```
Comment (smaslov-intel) [inline sycl/include/sycl/detail/pi.h:319]: could you rename these and use contiguous values from 0x1FFFF just below
 ```suggestion
  PI_EXT_DEVICE_INFO_ATOMIC_FENCE_ORDER_CAPABILITIES = 0x10114,
  PI_EXT_DEVICE_INFO_ATOMIC_FENCE_SCOPE_CAPABILITIES = 0x10115,
```

File: sycl/plugins/cuda/pi_cuda.cpp [hunk 4]
```diff
@@ -1315,6 +1315,10 @@ pi_result cuda_piDeviceGetInfo(pi_device device, pi_device_info param_name,
     return getInfo(param_value_size, param_value, param_value_size_ret,
                    capabilities);
   }
+  case PI_DEVICE_INFO_ATOMIC_FENCE_ORDER_CAPABILITIES:
+  case PI_DEVICE_INFO_ATOMIC_FENCE_SCOPE_CAPABILITIES:
+    // There is no way to query this in the backend
+    return PI_ERROR_INVALID_ARG_VALUE;
```
Comment (smaslov-intel) [inline sycl/plugins/cuda/pi_cuda.cpp:1321]: How is this error reported to the end user? Should we better use set a plugin specific error and have SYCL RT use piPluginGetLastError to retrieve/report it?

File: sycl/plugins/unified_runtime/ur/ur.hpp [hunk 5]
```diff
@@ -43,6 +43,10 @@ const int UR_EXT_DEVICE_INFO_FREE_MEMORY = UR_EXT_DEVICE_INFO_END - 13;
 // const int ZER_EXT_DEVICE_INFO_DEVICE_ID = UR_EXT_DEVICE_INFO_END - 14;
 // const int ZER_EXT_DEVICE_INFO_IMAGE_MAX_ARRAY_SIZE =
 //     UR_DEVICE_INFO_IMAGE_MAX_ARRAY_SIZE;
+const int UR_DEVICE_INFO_ATOMIC_FENCE_ORDER_CAPABILITIES =
+    UR_EXT_DEVICE_INFO_END - 16;
+const int UR_DEVICE_INFO_ATOMIC_FENCE_SCOPE_CAPABILITIES =
+    UR_EXT_DEVICE_INFO_END - 17;
```
Comment (smaslov-intel) [inline sycl/plugins/unified_runtime/ur/ur.hpp:49]: @kbenzie: please take this change into UR

File: sycl/plugins/unified_runtime/ur/adapters/level_zero/ur_level_zero.cpp [hunk 6]
```diff
@@ -1164,6 +1165,26 @@ UR_APIEXPORT ur_result_t UR_APICALL urDeviceGetInfo(
     // bfloat16 math functions are not yet supported on Intel GPUs.
     return ReturnValue(bool{false});
   }
+  case UR_DEVICE_INFO_ATOMIC_FENCE_ORDER_CAPABILITIES: {
+    // There are no explicit restrictions in L0 programming guide, so assume all
+    // are supported
+    pi_memory_order_capabilities result =
+        PI_MEMORY_ORDER_RELAXED | PI_MEMORY_ORDER_ACQUIRE |
+        PI_MEMORY_ORDER_RELEASE | PI_MEMORY_ORDER_ACQ_REL |
+        PI_MEMORY_ORDER_SEQ_CST;
```
Comment (smaslov-intel) [inline sycl/plugins/unified_runtime/ur/adapters/level_zero/ur_level_zero.cpp:1174]: You should write this in UR (extended as needed) and add a conversion in `piDeviceGetInfo`

File: sycl/plugins/unified_runtime/ur/adapters/level_zero/ur_level_zero.cpp [hunk 7]
```diff
@@ -5,6 +5,7 @@
 // SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
 //
 //===-----------------------------------------------------------------===//
+#include <sycl/detail/pi.h>
```
Comment (smaslov-intel) [inline sycl/plugins/unified_runtime/ur/adapters/level_zero/ur_level_zero.cpp:8]: UR should not include PI
```suggestion


```

File: sycl/include/sycl/detail/pi.h (hunk 3 above)
Comment (maarquitos14) [reply sycl/include/sycl/detail/pi.h:319]: The file already has `PI_DEVICE_INFO_ATOMIC_MEMORY_ORDER_CAPABILITIES` and `PI_DEVICE_INFO_ATOMIC_MEMORY_SCOPE_CAPABILITIES`. Should I change those to add `EXT` too?

File: sycl/plugins/cuda/pi_cuda.cpp (hunk 4 above)
Comment (maarquitos14) [reply sycl/plugins/cuda/pi_cuda.cpp]: @jchlanda @npmiller could you please take a look at the changes I did in HIP/CUDA to address this comment?

File: sycl/include/sycl/detail/pi.h (hunk 3 above)
Comment (smaslov-intel) [reply sycl/include/sycl/detail/pi.h]: It's up to you if you want to fix unrelated misses.

File: sycl/plugins/cuda/pi_cuda.cpp [hunk 8]
```diff
@@ -1315,6 +1315,12 @@ pi_result cuda_piDeviceGetInfo(pi_device device, pi_device_info param_name,
     return getInfo(param_value_size, param_value, param_value_size_ret,
                    capabilities);
   }
+  case PI_EXT_DEVICE_INFO_ATOMIC_FENCE_ORDER_CAPABILITIES:
+  case PI_EXT_DEVICE_INFO_ATOMIC_FENCE_SCOPE_CAPABILITIES:
+    // There is no way to query this in the backend
+    setErrorMessage("This backend does not support this query",
```
Comment (jchlanda) [inline sycl/plugins/cuda/pi_cuda.cpp:1321]: nit: I would mention the backend explicitly for a clean message sake, something along the lines of "PI HIP backend does not support this query".
Same for HIP backend.

**Review by jchlanda — APPROVED** [review]
PI HIP/CUDA looks good.

**Comment by maarquitos14** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1658

**Comment by maarquitos14** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1658

**Comment by maarquitos14** [comment]
@smaslov-intel I think all your comments have been addressed.

File: patch.txt
Comment (smaslov-intel) [inline patch.txt:1]: Please remove this file

File: sycl/plugins/unified_runtime/pi2ur.hpp [hunk 9]
```diff
@@ -483,11 +483,13 @@ inline pi_result piDeviceGetInfo(pi_device Device, pi_device_info ParamName,
...
+      {PI_EXT_DEVICE_INFO_ATOMIC_MEMORY_ORDER_CAPABILITIES,
+       (ur_device_info_t)UR_DEVICE_INFO_ATOMIC_MEMORY_ORDER_CAPABILITIES},
+      {PI_EXT_DEVICE_INFO_ATOMIC_MEMORY_SCOPE_CAPABILITIES,
        (ur_device_info_t)UR_DEVICE_INFO_ATOMIC_MEMORY_SCOPE_CAPABILITIES},
-      {PI_DEVICE_INFO_ATOMIC_FENCE_ORDER_CAPABILITIES,
+      {PI_EXT_DEVICE_INFO_ATOMIC_FENCE_ORDER_CAPABILITIES,
        (ur_device_info_t)UR_DEVICE_INFO_ATOMIC_FENCE_ORDER_CAPABILITIES},
-      {PI_DEVICE_INFO_ATOMIC_FENCE_SCOPE_CAPABILITIES,
+      {PI_EXT_DEVICE_INFO_ATOMIC_FENCE_SCOPE_CAPABILITIES,
        (ur_device_info_t)UR_DEVICE_INFO_ATOMIC_FENCE_SCOPE_CAPABILITIES},
```
Comment (smaslov-intel) [inline sycl/plugins/unified_runtime/pi2ur.hpp]: Since these return a bitset (and not single va

File: sycl/plugins/unified_runtime/pi2ur.hpp [hunk 10]
```diff
@@ -483,11 +483,13 @@ inline pi_result piDeviceGetInfo(pi_device Device, pi_device_info ParamName,
...
   };
```
Comment (smaslov-intel) [inline sycl/plugins/unified_runtime/pi2ur.hpp:494]: Since these "info" return a bit-set, I think we are missing a conversion (using converBitSet) of the result here: https://github.com/intel/llvm/blob/6490a36b6986e28fa4e5a786b4491a2cf47d8d5f/sycl/plugins/unified_runtime/pi2ur.hpp#L240

Comment (smaslov-intel) [reply sycl/plugins/unified_runtime/pi2ur.hpp:494]: Perhaps we need to explicitly handle all "info" parameters in `ur2piInfoValue` and avoid the conversions when not needed (for numerical values). This way new "info" conversions will less likely be missed (people will have to explicitly opt-out from it).

File: sycl/plugins/unified_runtime/pi2ur.hpp [hunk 11]
```diff
@@ -236,6 +236,56 @@ inline pi_result ur2piInfoValue(ur_device_info_t ParamName,
...
+                              pi_memory_order_capabilities>
+        Map = {
+            {UR_MEMORY_ORDER_CAPABILITY_FLAG_RELAXED, PI_MEMORY_ORDER_RELAXED},
+            {UR_MEMORY_ORDER_CAPABILITY_FLAG_ACQUIRE, PI_MEMORY_ORDER_ACQUIRE},
+            {UR_MEMORY_ORDER_CAPABILITY_FLAG_RELEASE, PI_MEMORY_ORDER_RELEASE},
+            {UR_MEMORY_ORDER_CAPABILITY_FLAG_ACQ_REL, PI_MEMORY_ORDER_ACQ_REL},
+            {UR_MEMORY_ORDER_CAPABILITY_FLAG_SEQ_CST, PI_MEMORY_ORDER_SEQ_CST},
+        };
+    return Value.convertBitSet(Map);
+  } else if (ParamName == UR_DEVICE_INFO_ATOMIC_FENCE_SCOPE_CAPABILITIES) {
```
Comment (smaslov-intel) [inline sycl/plugins/unified_runtime/pi2ur.hpp:275]: please merge with line 250

**Review by smaslov-intel — APPROVED** [review]
LGTM. thanks!

**Comment by maarquitos14** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1658

File: sycl/plugins/opencl/pi_opencl.cpp [hunk 12]
```diff
@@ -282,8 +282,7 @@ pi_result piDeviceGetInfo(pi_device device, pi_device_info paramName,
     // For details about Intel UUID extension, see
     // sycl/doc/extensions/supported/sycl_ext_intel_device_info.md
   case PI_DEVICE_INFO_UUID:
-    return PI_ERROR_INVALID_VALUE;
```
Comment (AlexeySachkov) [inline sycl/plugins/opencl/pi_opencl.cpp:285]: I believe that this line shouldn't be removed

File: sycl/source/detail/device_info.hpp [hunk 13]
```diff
@@ -1025,13 +1051,27 @@ get_device_info_host<info::device::atomic_memory_order_capabilities>() {
           memory_order::acq_rel, memory_order::seq_cst};
 }
 
+template <>
+inline std::vector<memory_order>
+get_device_info_host<info::device::atomic_fence_order_capabilities>() {
```
Comment (AlexeySachkov) [inline sycl/source/detail/device_info.hpp:1056]: I wonder when we will be able to stop specializing that for host device, because it doesn't really exists anymore

File: sycl/plugins/unified_runtime/pi2ur.hpp (hunk 10 above)
Comment (jandres742) [reply sycl/plugins/unified_runtime/pi2ur.hpp:522]: @smaslov-intel : you mean to handle both input and output mappings, and have ur2piInfoValue and pi2urInfoValue?

**Comment by maarquitos14** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1658

**Comment by maarquitos14** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1658

**Comment by maarquitos14** [comment]
Friendly ping @intel/llvm-reviewers-runtime.

**Review by jandres742 — COMMENTED** [review]
+1 on UR/L0 related changes.

**Review by steffenlarsen — APPROVED** [review]
LGTM!

File: sycl/include/sycl/detail/pi.h (hunk 2 above)
Comment (kbenzie) [reply sycl/include/sycl/detail/pi.h]: Tracking in https://github.com/oneapi-src/unified-runtime/issues/399
