### PR TITLE
[SYCL][L0][CUDA][HIP] Fix PI_KERNEL_GROUP_INFO_GLOBAL_WORK_SIZE queries

### LINKED ISSUE #8766: CUDA and HIP backends do not support PI_KERNEL_GROUP_INFO_GLOBAL_WORK_SIZE
The CUDA and HIP backends do not currently handle `PI_KERNEL_GROUP_INFO_GLOBAL_WORK_SIZE` in `piKernelGetGroupInfo`. This causes SYCL/Basic/kernel_info.cpp in the test-suite to fail.

### PR DESCRIPTION
**Pull request by abagusetty**
Address kernel query `global_work_size` for L0, CUDA, HIP from `PI_KERNEL_GROUP_INFO_GLOBAL_WORK_SIZE`
Fixes #8766 
For instance (for X-dimension)
L0: `maxGroupSizeX * maxGroupCountX`
CUDA: `CU_DEVICE_ATTRIBUTE_MAX_BLOCK_DIM_X * CU_DEVICE_ATTRIBUTE_MAX_GRID_DIM_X`

### CODE REVIEW

**Comment by abagusetty** [comment]
Fixes #8766

**Comment by abagusetty** [comment]
/verify with https://github.com/intel/llvm-test-suite/pull/1694

**Comment by abagusetty** [comment]
> 

Thanks, I stumbled upon that too and looked at the wording in Spec, which made me think it could be the max global limits.
```
The exact semantics of this descriptor are defined by each SYCL backend specification, but the intent is to return the kernel’s maximum global work size.
```

**Comment by jinz2014** [comment]
The global work sizes from the query will be the same for any kernels. Right ?

**Comment by abagusetty** [comment]
> The global work sizes from the query will be the same for any kernels. Right ?

Yes, since the descriptor is a kernel_device_specific one: Any kernel from (custom device type or a built-in kernel) possibly returns the info of device specific global-work-sizes which in turn should be the same for all the kernels IMO.

File: sycl/plugins/level_zero/pi_level_zero.cpp [hunk 1]
```diff
@@ -4228,13 +4228,15 @@ pi_result piKernelGetGroupInfo(pi_kernel Kernel, pi_device Device,
   std::shared_lock<pi_shared_mutex> Guard(Kernel->Mutex);
   switch (ParamName) {
   case PI_KERNEL_GROUP_INFO_GLOBAL_WORK_SIZE: {
-    // TODO: To revisit after level_zero/issues/262 is resolved
```
Comment (smaslov-intel) [inline sycl/plugins/level_zero/pi_level_zero.cpp:4231]: Do you have a link to this issue?

Comment (abagusetty) [reply sycl/plugins/level_zero/pi_level_zero.cpp:4231]: Glad you've asked. I've tried to find it in `[level_zero](https://github.com/oneapi-src/level-zero/issues)` and [L)-spec](https://github.com/oneapi-src/level-zero-spec/issues). Couldn't find an issue related to this. There were any issue with tags greater than 150s. 

Looked into compute-RT and found this: https://github.com/intel/compute-runtime/issues/262. Didn't really look related.

File: sycl/plugins/cuda/pi_cuda.hpp [hunk 2]
```diff
@@ -42,6 +42,11 @@
 #include <unordered_map>
 #include <vector>
 
+// Helper for one-liner validation
+#define PI_ASSERT(condition, error)                                            \
```
Comment (jchlanda) [inline sycl/plugins/cuda/pi_cuda.hpp:46]: It's a bit misleading, as it does not assert on the condition, maybe consider renaming it?

Comment (abagusetty) [reply sycl/plugins/cuda/pi_cuda.hpp]: `PI_ASSERT` to `PI_ERR_CHECK`

File: sycl/plugins/hip/pi_hip.cpp [hunk 3]
```diff
@@ -2857,7 +2857,7 @@ pi_result hip_piEnqueueKernelLaunch(
   // Preconditions
   assert(command_queue != nullptr);
```
Comment (jchlanda) [inline sycl/plugins/hip/pi_hip.cpp:2858]: I'm not sure what is the exact rule for using the new macro, but if it's meant to validate the existence of the object/pointer, you'd probably want it here as well as for `global_work_offset`?

**Review by jchlanda — COMMENTED** [review]
The query (`PI_KERNEL_GROUP_INFO_GLOBAL_WORK_SIZE`) for hip and cuda LGTM.

I'm not sure about the `PI_ERR_CHECK` macro.
In my view it doesn't belong in this PR and should be separated out to its own PR, furthermore it is inconsistent, `pfn_notify` gets both `PI_ERR_CHECK` and `assert` treatment depending on the plugin backend. If the intention is to validate the pointer/object there are multiple cases missed (on the other hand it's also used to check the range of value - in which case there are even more entries still using `assert`).

File: sycl/plugins/hip/pi_hip.cpp (hunk 3 above)
Comment (abagusetty) [reply sycl/plugins/hip/pi_hip.cpp:2858]: Correct, I did miss this one. I was trying to wrap several of the nullptr checks and invalid cases to align with PI error-reporting code. But I agree to separate those changes into a separate PR.

Comment (jchlanda) [reply sycl/plugins/hip/pi_hip.cpp:2858]: 👍 thank you.

**Comment by abagusetty** [comment]
Gentle ping @smaslov-intel  @jchlanda

File: sycl/plugins/level_zero/pi_level_zero.cpp (hunk 1 above)
Comment (smaslov-intel) [reply sycl/plugins/level_zero/pi_level_zero.cpp:4237]: The issue was closed before the remaining open ones were moved to a new location. So we will not be able to find what it was, I am afraid. The change looks good to me but I'd want @jandres742 to confirm.

Comment (jandres742) [reply sycl/plugins/level_zero/pi_level_zero.cpp:4237]: why are we multiplying? what is the meaning PI_KERNEL_GROUP_INFO_GLOBAL_WORK_SIZE?

In L0 we have maxTotalGroupSize, would that be what we need here?
https://spec.oneapi.io/level-zero/latest/core/api.html?highlight=maxtotalgroupsize#_CPPv4N30ze_device_compute_properties_t17maxTotalGroupSizeE

Comment (abagusetty) [reply sycl/plugins/level_zero/pi_level_zero.cpp:4237]: @jandres742 Thanks for pointing to the documentation. These are the wordings from the spec `The exact semantics of this descriptor are defined by each SYCL backend specification, but the intent is to return the kernel’s maximum global work size.` 

Since the return is per-dimension (i.e., a `sycl::range<3>`), I was multiplying for each dimension. I looked into `maxTotalGroupSize` and that looked like for "max size per compute work-group" and it might not be a functionally equivalent one. The functionality was for the "global maximum iteration limits per dimension"

Comment (jandres742) [reply sycl/plugins/level_zero/pi_level_zero.cpp:4237]: thanks @abagusetty . I read the definition of CL_KERNEL_GLOBAL_WORK_SIZE , which would be equivalent, and proposed change seems correct.

FYI: I dont see CL_KERNEL_GLOBAL_WORK_SIZE implemented in Intel OCL GPU driver, so don't know what we are returning for the OpenCL GPU backend.

**Review by jandres742 — COMMENTED** [review]
+1 on L0 changes.

**Review by smaslov-intel — APPROVED** [review]

**Review by steffenlarsen — APPROVED** [review]
Sorry for the delay. I think these changes look good. I am a little curious what built-in kernels they would apply to, but I assume CUDA, HIP and L0 guarantee full possible work-sizes either way.

**Comment by abagusetty** [comment]
> Sorry for the delay. I think these changes look good. I am a little curious what built-in kernels they would apply to, but I assume CUDA, HIP and L0 guarantee full possible work-sizes either way.

Thanks for the feed back on the built-ins, I too stumbled upon that a bit: Just convinced myself that they see the complete device limits.
