### PR TITLE
[Clang][Test] Remove sycl-bc-device-libraries.cpp's dependency on libspirv files

### LINKED ISSUE #20784: Found one lit test ` Clang :: Driver/sycl-bc-device-libraries.cpp` run failed in the latest code repo
code repo commit id(6dd1bc3465612188fda216a208341869df5d7d8b ) by now on default `sycl` branch:
```
commit 6dd1bc3465612188fda216a208341869df5d7d8b (HEAD -> sycl, tag: sycl-web/sycl-latest-good, tag: nightly-2025-11-30, tag: nightly-2025-11-29, origin/sycl, origin/HEAD)
Author: Łukasz Ślusarczyk <lukasz.slusarczyk@intel.com>
Date:   Fri Nov 28 16:54:35 2025 +0100

    [SYCL] Optimize calling UR functions (#20776)

    _checkUrResult_ function was made as short as possible by moving away
    all error handling to a separate non-inlined function and keeping common
    success path tiny and additionally optimized by compiler
    __builtin_expect. Also a few more simple inlines were added.
```
Host machine: Ubuntu 22.04.5 LTS

run lit test command:
```
export DPCPP_HOME=/path/to/intel_llvm_workspace

mkdir $DPCPP_HOME
cd $DPCPP_HOME

python3 $DPCPP_HOME/llvm/buildbot/configure.py --cuda -o $DPCPP_HOME/build -t Release
python3 $DPCPP_HOME/llvm/buildbot/compile.py -o $DPCPP_HOME/build
python3 $DPCPP_HOME/llvm/buildbot/check.py -o $DPCPP_HOME/build

export PATH=$DPCPP_HOME/build/install/bin:$PATH
export LD_LIBRARY_PATH=$DPCPP_HOME/build/install/lib:$LD_LIBRARY_PATH
export CPATH=$DPCPP_HOME/build/install/include:$CPATH

```
Then meet the lit test failure `Clang :: Driver/sycl-bc-device-libraries.cpp`shown as follows:

```

FAIL: Clang :: Driver/sycl-bc-device-libraries.cpp (13314 of 92047)
******************** TEST 'Clang :: Driver/sycl-bc-device-libraries.cpp' FAILED ********************
Exit Code: 1

Command Output (stdout):
--
# RUN: at line 4
/localdisk/chenweis/intel_llvm_workspace/build/bin/clang -### -fsycl --offload-new-driver    -fsycl-targets=nvptx64-nvidia-cuda    --cuda-path=/localdisk/chenweis/intel_llvm_workspace/llvm/clang/test/Driver/Inputs/CUDA_102/usr/local/cuda    /localdisk/chenweis/intel_llvm_workspace/llvm/clang/test/Driver/sycl-bc-device-libraries.cpp 2>&1 | /localdisk/chenweis/intel_llvm_workspace/build/bin/FileCheck -check-prefix=CHECK-NVPTX-BC /localdisk/chenweis/intel_llvm_workspace/llvm/clang/test/Driver/sycl-bc-device-libraries.cpp
# executed command: /localdisk/chenweis/intel_llvm_workspace/build/bin/clang '-###' -fsycl --offload-new-driver -fsycl-targets=nvptx64-nvidia-cuda --cuda-path=/localdisk/chenweis/intel_llvm_workspace/llvm/clang/test/Driver/Inputs/CUDA_102/usr/local/cuda /localdisk/chenweis/intel_llvm_workspace/llvm/clang/test/Driver/sycl-bc-device-libraries.cpp
# executed command: /localdisk/chenweis/intel_llvm_workspace/build/bin/FileCheck -check-prefix=CHECK-NVPTX-BC /localdisk/chenweis/intel_llvm_workspace/llvm/clang/test/Driver/sycl-bc-device-libraries.cpp
# RUN: at line 9
/localdisk/chenweis/intel_llvm_workspace/build/bin/clang --driver-mode=cl -### -fsycl --offload-new-driver    -fsycl-targets=nvptx64-nvidia-cuda    --cuda-path=/localdisk/chenweis/intel_llvm_workspace/llvm/clang/test/Driver/Inputs/CUDA_102/usr/local/cuda    /localdisk/chenweis/intel_llvm_workspace/llvm/clang/test/Driver/sycl-bc-device-libraries.cpp 2>&1 | /localdisk/chenweis/intel_llvm_workspace/build/bin/FileCheck -check-prefix=CHECK-NVPTX-BC /localdisk/chenweis/intel_llvm_workspace/llvm/clang/test/Driver/sycl-bc-device-libraries.cpp
# executed command: /localdisk/chenweis/intel_llvm_workspace/build/bin/clang --driver-mode=cl '-###' -fsycl --offload-new-driver -fsycl-targets=nvptx64-nvidia-cuda --cuda-path=/localdisk/chenweis/intel_llvm_workspace/llvm/clang/test/Driver/Inputs/CUDA_102/usr/local/cuda /localdisk/chenweis/intel_llvm_workspace/llvm/clang/test/Driver/sycl-bc-device-libraries.cpp
# executed command: /localdisk/chenweis/intel_llvm_workspace/build/bin/FileCheck -check-prefix=CHECK-NVPTX-BC /localdisk/chenweis/intel_llvm_workspace/llvm/clang/test/Driver/sycl-bc-device-libraries.cpp
# RUN: at line 18
/localdisk/chenweis/intel_llvm_workspace/build/bin/clang -### -fsycl --offload-new-driver    -fsycl-targets=amdgcn-amd-amdhsa    -Xsycl-target-backend=amdgcn-amd-amdhsa --offload-arch=gfx900    --rocm-path=/localdisk/chenweis/intel_llvm_workspace/llvm/clang/test/Driver/Inputs/rocm    /localdisk/chenweis/intel_llvm_workspace/llvm/clang/test/Driver/sycl-bc-device-libraries.cpp 2>&1 | /localdisk/chenweis/intel_llvm_workspace/build/bin/FileCheck -check-prefix=CHECK-AMD-BC /localdisk/chenweis/intel_llvm_workspace/llvm/clang/test/Driver/sycl-bc-device-libraries.cpp
# executed command: /localdisk/chenweis/intel_llvm_workspace/build/bin/clang '-###' -fsycl --offload-new-driver -fsycl-targets=amdgcn-amd-amdhsa -Xsycl-target-backend=amdgcn-amd-amdhsa --offload-arch=gfx900 --rocm-path=/localdisk/chenweis/intel_llvm_workspace/llvm/clang/test/Driver/Inputs/rocm /localdisk/chenweis/intel_llvm_workspace/llvm/clang/test/Driver/sycl-bc-device-libraries.cpp
# note: command had no output on stdout or stderr
# error: command failed with exit status: 1
# executed command: /localdisk/chenweis/intel_llvm_workspace/build/bin/FileCheck -check-prefix=CHECK-AMD-BC /localdisk/chenweis/intel_llvm_workspace/llvm/clang/test/Driver/sycl-bc-device-libraries.cpp

--

********************
********************
Failed Tests (1):
  Clang :: Driver/sycl-bc-device-libraries.cpp


Testing Time: 155.22s

```

Pls take a look, thanks.

### PR DESCRIPTION
**Pull request by wenju-he**
Also add `-fgpu-rdc` to fix `Unknown command line argument '-amdgpu-internalize-symbols'` error when generating %t.amd.o.

Closes #20784

### CODE REVIEW

File: clang/test/Driver/sycl-bc-device-libraries.cpp [hunk 1]
```diff
@@ -1,27 +1,34 @@
 /// Test that SYCL bitcode device libraries are properly separated for NVIDIA and AMD targets.
 
-/// Check devicelib and libspirv are linked for nvptx.
+/// amdgpu-registered-target is required for generating %t.amd.o.
+// REQUIRES: amdgpu-registered-target
```
Comment (mdtoguchi) [inline clang/test/Driver/sycl-bc-device-libraries.cpp]: This seems restrictive for any tests that are testing nvidia targets only.  Is that scenario important?

Comment (wenju-he) [reply clang/test/Driver/sycl-bc-device-libraries.cpp]: > This seems restrictive for any tests that are testing nvidia targets only. Is that scenario important?

done, removed `REQUIRES: amdgpu-registered-target` in https://github.com/intel/llvm/pull/20791/commits/7e3ed1b1e78e9098394e24e132102d374428c68d.

Added -fgpu-rdc as a workaround to prevent the Clang driver from passing `-amdgpu-internalize-symbols` to LLVM.
