### PR TITLE
[SYCL][CUDA] Handle the case of not having any CUDA device

### LINKED ISSUE #1198: Using cl::sycl::platform::get_platforms() on a machine without a CUDA or OpenCL device
I am running some tests at the moment with the HEAD of the sycl branch (https://github.com/intel/llvm/commit/65da01b2a2912237048d61ec0c511dac6346a489). I was hoping to build the compiler on CentOS 7 such that it could be used on machines that have no CUDA or OpenCL devices, in which case the produced executables could just fall back on the host device. (As is the intention with SYCL...)

Unfortunately this doesn't seem to work. :frowning:

The compiler itself seems to be fine, it is functional after my build.

```
[bash][lxplus739]:~ > clang++ -v
clang version 11.0.0 (/home/krasznaa/software/intel/llvm/clang 65da01b2a2912237048d61ec0c511dac6346a489)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /afs/cern.ch/user/k/krasznaa/work/public/clang/11.0.0-65da01b/x86_64-centos7-gcc8-opt/bin
Found candidate GCC installation: /afs/cern.ch/work/k/krasznaa/public/gcc/8.3.0/x86_64-centos7/lib/gcc/x86_64-pc-linux-gnu/8.3.0
Selected GCC installation: /afs/cern.ch/work/k/krasznaa/public/gcc/8.3.0/x86_64-centos7/lib/gcc/x86_64-pc-linux-gnu/8.3.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
Found CUDA installation: /afs/cern.ch/work/k/krasznaa/public/cuda/10.1.243/x86_64-centos7, version 10.1
[bash][lxplus739]:~ >
```
I was trying to compile the following very simple executable with it:

```c++
// SYCL include(s).
#include <CL/sycl.hpp>

// System include(s).
#include <iostream>

int main() {

   // Loop over all available SYCL platforms.
   for( const cl::sycl::platform& platform :
        cl::sycl::platform::get_platforms() ) {

      // Print some information about the platform.
      std::cout << "============ Platform ============" << std::endl;
      std::cout << " Name   : "
                << platform.get_info< cl::sycl::info::platform::name >()
                << std::endl;
      std::cout << " Vendor : "
                << platform.get_info< cl::sycl::info::platform::vendor >()
                << std::endl;
      std::cout << " Version: "
                << platform.get_info< cl::sycl::info::platform::version >()
                << std::endl;

      // Loop over all devices available from this platform.
      for( const cl::sycl::device& device : platform.get_devices() ) {

         // Print some information about the device.
         std::cout << "------------- Device -------------" << std::endl;
         std::cout << " Name   : "
                   << device.get_info< cl::sycl::info::device::name >()
                   << std::endl;
         std::cout << " Vendor : "
                   << device.get_info< cl::sycl::info::device::vendor >()
                   << std::endl;
         std::cout << " Version: "
                   << device.get_info< cl::sycl::info::device::version >()
                   << std::endl;
      }
   }

   // Return gracefully.
   return 0;
}
```

It compiles just fine, but it is unable to run. :frowning:

```
[bash][lxplus739]:cudaSycl > clang++ -g -fsycl -o syclinfo syclinfo.cxx 
[bash][lxplus739]:cudaSycl > ./syclinfo 

PI CUDA ERROR:
        Value:           100
        Name:            CUDA_ERROR_NO_DEVICE
        Description:     no CUDA-capable device is detected
        Function:        operator()
        Source Location: /home/krasznaa/software/intel/llvm/sycl/plugins/cuda/pi_cuda.cpp:546

terminate called after throwing an instance of 'cl::sycl::runtime_error'
  what():  OpenCL API failed. OpenCL API returns: -999 (Unknown OpenCL error code) -999 (Unknown OpenCL error code)
Aborted (core dumped)
[bash][lxplus739]:cudaSycl >
```

The exception itself is coming from:

```
[bash][lxplus739]:cudaSycl > gdb ./syclinfo
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-115.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /afs/cern.ch/user/k/krasznaa/ATLAS/sw/projects/cudaSycl/syclinfo...done.
(gdb) catch throw
Function "__cxa_throw" not defined.
Catchpoint 1 (throw)
(gdb) run
Starting program: /afs/cern.ch/user/k/krasznaa/ATLAS/sw/projects/cudaSycl/./syclinfo 
warning: File "/afs/cern.ch/work/k/krasznaa/public/gcc/8.3.0/x86_64-centos7/lib64/libstdc++.so.6.0.25-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/usr/bin/mono-gdb.py:/usr/lib/golang/src/runtime/runtime-gdb.py".
To enable execution of this file add
        add-auto-load-safe-path /afs/cern.ch/work/k/krasznaa/public/gcc/8.3.0/x86_64-centos7/lib64/libstdc++.so.6.0.25-gdb.py
line to your configuration file "/afs/cern.ch/user/k/krasznaa/.gdbinit".
To completely disable this security protection add
        set auto-load safe-path /
line to your configuration file "/afs/cern.ch/user/k/krasznaa/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
        info "(gdb)Auto-loading safe path"
warning: File "/afs/cern.ch/work/k/krasznaa/public/clang/11.0.0-65da01b/x86_64-centos7-gcc8-opt/lib/libsycl.so-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/usr/bin/mono-gdb.py:/usr/lib/golang/src/runtime/runtime-gdb.py".
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Missing separate debuginfo for /afs/cern.ch/work/k/krasznaa/public/cuda/10.1.243/x86_64-centos7/lib64/libcuda.so.1
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/03/576a4f319db6975143582d3c29f08c5eefb030.debug

PI CUDA ERROR:
        Value:           100
        Name:            CUDA_ERROR_NO_DEVICE
        Description:     no CUDA-capable device is detected
        Function:        operator()
        Source Location: /home/krasznaa/software/intel/llvm/sycl/plugins/cuda/pi_cuda.cpp:546

Catchpoint 1 (exception thrown), __cxxabiv1::__cxa_throw (obj=0x62b2e0, tinfo=0x7ffff6442ae0 <typeinfo for _pi_result>, dest=0x0)
    at ../../../../gcc-8.3.0/libstdc++-v3/libsupc++/eh_throw.cc:78
78      ../../../../gcc-8.3.0/libstdc++-v3/libsupc++/eh_throw.cc: No such file or directory.
Missing separate debuginfos, use: debuginfo-install glibc-2.17-292.el7.x86_64
(gdb) c
Continuing.
Catchpoint 1 (exception thrown), __cxxabiv1::__cxa_throw (obj=0x62b2e0, 
    tinfo=0x7ffff7539870 <typeinfo for cl::sycl::runtime_error>, dest=0x7ffff721f3f0 <cl::sycl::runtime_error::~runtime_error()>)
    at ../../../../gcc-8.3.0/libstdc++-v3/libsupc++/eh_throw.cc:78
78      in ../../../../gcc-8.3.0/libstdc++-v3/libsupc++/eh_throw.cc
(gdb) bt
#0  __cxxabiv1::__cxa_throw (obj=0x62b2e0, tinfo=0x7ffff7539870 <typeinfo for cl::sycl::runtime_error>, 
    dest=0x7ffff721f3f0 <cl::sycl::runtime_error::~runtime_error()>)
    at ../../../../gcc-8.3.0/libstdc++-v3/libsupc++/eh_throw.cc:78
#1  0x00007ffff70ba859 in void cl::sycl::detail::plugin::checkPiResult<cl::sycl::runtime_error>(_pi_result) const [clone .constprop.764] [clone .cold.777] ()
   from /afs/cern.ch/user/k/krasznaa/work/public/clang/11.0.0-65da01b/x86_64-centos7-gcc8-opt/lib/libsycl.so
#2  0x00007ffff725fe92 in cl::sycl::detail::platform_impl::get_platforms() ()
   from /afs/cern.ch/user/k/krasznaa/work/public/clang/11.0.0-65da01b/x86_64-centos7-gcc8-opt/lib/libsycl.so
#3  0x00007ffff72d01a9 in cl::sycl::platform::get_platforms() ()
   from /afs/cern.ch/user/k/krasznaa/work/public/clang/11.0.0-65da01b/x86_64-centos7-gcc8-opt/lib/libsycl.so
#4  0x000000000040112b in main () at syclinfo.cxx:13
(gdb)
```

There seem to be multiple things wrong here:
  - The CUDA plugin should really not print any error messages just because it can't find a CUDA device. Since the whole point of using SYCL is portability, right?
  - Even if it prints a warning (error), there's really no reason for it to kill the application. As far as I can see, the exception gets thrown because of the CUDA issue. Though I'm not 100% sure about that.

Note that I didn't even explicitly tell `clang++` to build NVPTX code into my binary. Which makes this behaviour just the more annoying. :frowning:

Cc. @fwyzard. I think you'll also be interested in this Andrea. :wink:

### PR DESCRIPTION
**Pull request by fwyzard**
If there are no CUDA devices, do not return any CUDA-based SYCL platform rather than aborting or throwing an exception.

Fixes #1198.

### CODE REVIEW

File: sycl/plugins/cuda/pi_cuda.cpp [hunk 1]
```diff
@@ -528,43 +530,52 @@ pi_result cuda_piPlatformsGet(pi_uint32 num_entries, pi_platform *platforms,
...
-                CUdevice device;
-                err = PI_CHECK_ERROR(cuDeviceGet(&device, i));
-                platformId.devices_.emplace_back(
-                    new _pi_device{device, &platformId});
-              }
-            } catch (...) {
-              // Clear and rethrow to allow retry
-              platformId.devices_.clear();
-              throw;
+    std::call_once(
```
Comment (Ruyk) [inline sycl/plugins/cuda/pi_cuda.cpp]: In the original code, the `call_once` that triggers `cuInit` is never called if the SYCL RT doesn't pass the `pi_platform *platforms` parameter, e.g. when just querying the number of platforms available.
In this patch,  `cuInit` is always called, even when just querying the number of platforms. 

This maybe breaks some unit tests for the pi cuda backend, but they are disabled at the moment. @bjoernknafla / @Alexander-Johnston  : maybe make a note of this change for when resuming the work on the unit tests?

Comment (fwyzard) [reply sycl/plugins/cuda/pi_cuda.cpp]: One difference will be that, on a machine without CUDA devices, this will now return 0 platforms.

File: sycl/plugins/cuda/pi_cuda.cpp [hunk 2]
```diff
@@ -528,43 +530,52 @@ pi_result cuda_piPlatformsGet(pi_uint32 num_entries, pi_platform *platforms,
...
 
   try {
-    static constexpr pi_uint32 numPlatforms = 1;
+    static std::once_flag initFlag;
+    static pi_uint32 numPlatforms = 1;
+    static _pi_platform platformId;
 
-    if (num_platforms != nullptr) {
-      *num_platforms = numPlatforms;
+    if (num_entries == 0 and platforms != nullptr) {
```
Comment (bjoernknafla) [inline sycl/plugins/cuda/pi_cuda.cpp]: Surprised by the `and` - have never seen this before. What are the benefits (other than readability)?

File: sycl/plugins/cuda/pi_cuda.cpp [hunk 3]
```diff
@@ -34,6 +34,8 @@ pi_result map_error(CUresult result) {
     return PI_INVALID_OPERATION;
   case CUDA_ERROR_INVALID_CONTEXT:
     return PI_INVALID_CONTEXT;
+  case CUDA_ERROR_NO_DEVICE:
```
Comment (bjoernknafla) [inline sycl/plugins/cuda/pi_cuda.cpp]: This error code seems to only come up with CUDA-OpenGL interop according to the docs - is that something you see otherwise in the wild?

File: sycl/plugins/cuda/pi_cuda.cpp (hunk 2 above)
Comment (fwyzard) [reply sycl/plugins/cuda/pi_cuda.cpp]: Do you mean the use of `and` rather than `&&` ?
Just readability AFAIK (see e.g. https://en.cppreference.com/w/cpp/language/operator_alternative)

File: sycl/plugins/cuda/pi_cuda.cpp (hunk 3 above)
Comment (fwyzard) [reply sycl/plugins/cuda/pi_cuda.cpp]: Sorry - this is actually a leftover from the first attempt I made, that was returning `PI_INVALID_PLATFORM` if there are no CUDA devices.

It should be fine to drop these two lines.

Comment (bjoernknafla) [reply sycl/plugins/cuda/pi_cuda.cpp]: Wondering if `PI_INVALID_PLATFORM` is the best match for the device error as I am unsure which OpenCL (extension) call would relate to OpenGL in this case?

File: sycl/plugins/cuda/pi_cuda.cpp [hunk 4]
```diff
@@ -528,43 +528,52 @@ pi_result cuda_piPlatformsGet(pi_uint32 num_entries, pi_platform *platforms,
...
+              err = PI_CHECK_ERROR(cuDeviceGet(&device, i));
+              platformId.devices_.emplace_back(
+                  new _pi_device{device, &platformId});
             }
-          },
-          err);
+          } catch (...) {
+            // Clear and rethrow to allow retry
+            platformId.devices_.clear();
+            throw;
```
Comment (bjoernknafla) [inline sycl/plugins/cuda/pi_cuda.cpp]: Nitpicking  but wondering if we should catch `std::bad_alloc` to react to allocation fails by throwing `PI_OUT_OF_HOST_MEMORY`?

File: sycl/plugins/cuda/pi_cuda.cpp (hunk 1 above)
Comment (bjoernknafla) [reply sycl/plugins/cuda/pi_cuda.cpp]: Famous last words though I do not think that calling `cuInit` earlier than before will have an effect on the unit tests (the `call_once` should be enough from stopping bad behavior).

Comment (bjoernknafla) [reply sycl/plugins/cuda/pi_cuda.cpp]: We have a not yet shared patch for dealing with not finding platforms and/or devices.

Comment (bjoernknafla) [reply sycl/plugins/cuda/pi_cuda.cpp]: PS: I like this change a lot!

File: sycl/plugins/cuda/pi_cuda.cpp [hunk 5]
```diff
@@ -528,43 +528,52 @@ pi_result cuda_piPlatformsGet(pi_uint32 num_entries, pi_platform *platforms,
...
-              }
-            } catch (...) {
-              // Clear and rethrow to allow retry
-              platformId.devices_.clear();
-              throw;
+    std::call_once(
+        initFlag,
+        [](pi_result &err) {
+          CUresult result = cuInit(0);
+          if (result == CUDA_ERROR_NO_DEVICE) {
```
[the remark this answers is not in the document]
Comment (fwyzard) [reply sycl/plugins/cuda/pi_cuda.cpp]: it's not in the docs, but it is returned when there are no available devices (I'm testing with CUDA 10.2).

[the remark this answers is not in the document]
Comment (fwyzard) [reply sycl/plugins/cuda/pi_cuda.cpp]: The idea was to special case a working installation which simply has no devices (for example because of `CUDA_VISIBLE_DEVICES=`).

I guess it also makes sense not to return the platform, instead of calling`abort()`, if `cuInit()` fails for other reasons.

I can make the change (and remove the call to `PI_CHECK_ERROR(result)`) if this is the preferred behaviour.

File: sycl/plugins/cuda/pi_cuda.cpp [hunk 6]
```diff
@@ -528,43 +528,52 @@ pi_result cuda_piPlatformsGet(pi_uint32 num_entries, pi_platform *platforms,
...
+            numPlatforms = 0;
+            return;
+          };
+          err = PI_CHECK_ERROR(result);
+
+          int numDevices = 0;
+          err = PI_CHECK_ERROR(cuDeviceGetCount(&numDevices));
+          platformId.devices_.reserve(numDevices);
```
[the remark this answers is not in the document]
Comment (fwyzard) [reply sycl/plugins/cuda/pi_cuda.cpp]: Sure.

By the way, for consistency should the plugin return no platforms if `cuInit()` succeeds but `cuDeviceGetCount(...)` returns 0 devices ?

File: sycl/plugins/cuda/pi_cuda.cpp (hunk 4 above)
Comment (fwyzard) [reply sycl/plugins/cuda/pi_cuda.cpp]: Sure.

File: sycl/plugins/cuda/pi_cuda.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (krasznaa) [reply sycl/plugins/cuda/pi_cuda.cpp]: I would argue that `cuInit()` should be allowed to fail for **any reason**. At that point we should just not get any CUDA devices at runtime. The application should still be allowed to sue OpenCL/host devices at that point.

So yeah, I would just check with `CUDA_SUCCESS`.

**Comment by bjoernknafla** [comment]
Should we check in `cuda_piDevicesGet` if there is a platform and return `PI_INVALID_PLATFORM` otherwise?

**Comment by bjoernknafla** [comment]
Studying [OpenCL 2.1 specs](https://www.khronos.org/registry/OpenCL/sdk/2.1/docs/man/xhtml/clGetPlatformIDs.html):
* Without the `cl_khr_icd` extension (which we do not report/support) there is now way to not return a platform without an error code, but no error code exists to report that a platform does not exist...

To not deviate too much from the OpenCL spec, can we really support a `0` for number of platforms? Or do we always have to return a platform but then not report any devices?

**Comment by fwyzard** [comment]
Is it possible to call `cuda_piDevicesGet` if `cuda_piPlatformsGet` does not return any platforms ?

**Comment by bjoernknafla** [comment]
No, though at the moment we always return a platform - even if we set the internal number to `0` - and I think we have to return a platform if we do not want to return an error. And I believe we do not want to return an error if there are no devices as this might trip up an implementation that is ok with finding any platform with devices even if CUDA isn't the one.

**Comment by fwyzard** [comment]
For what is worth, my interpretation is that `clGetPlatformIDs` returns:
   * `CL_SUCCESS` if the function is executed successfully.
   * `CL_INVALID_VALUE` if `num_entries` is equal to zero and platforms is not `NULL` or if both `num_platforms` and `platforms` are `NULL`.
   * `CL_OUT_OF_HOST_MEMORY` if there is a failure to allocate resources required by the OpenCL implementation on the host.

If the `cl_khr_icd` extension is enabled, it returns:
   * `CL_SUCCESS` if the function is executed successfully and there are a non zero number of platforms available.
   * `CL_PLATFORM_NOT_FOUND_KHR` if no platforms are found.


I do not know if "the function is executed successfully" implies that at least one platform with at least one device should be available.

**Comment by bjoernknafla** [comment]
Just checked [the only part of SYCL that calls piPlatformsGet](https://github.com/intel/llvm/blob/sycl/sycl/source/detail/platform_impl.cpp#L33) and it checks the number of returned platforms.

This should therefore be fine for the SYCL implementation but we have to check out unit tests.

**Comment by bjoernknafla** [comment]
@fwyzard  thank you for the back and forth to allow me to wrap my head around the intricacies!

**Comment by fwyzard** [comment]
My pleasure.

By the way, here is what I get on a machine with both OpenCL and CUDA available:
```
Available SYCL platforms:
  - Intel(R) OpenCL, driver version OpenCL 2.1 LINUX
    - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz, driver version 2020.9.1.0.18

  - Intel(R) OpenCL HD Graphics, driver version OpenCL 2.1 
    - Intel(R) Gen9 HD Graphics NEO, driver version 20.07.15711

  - NVIDIA CUDA, driver version CUDA 10.20
    - Tesla K40c, driver version CUDA 10.20

  - SYCL host platform, driver version 1.2
    - SYCL host device, driver version 1.2
```

and ere is what I get with the proposed changes, if I "hide" the NVIDIA GPU via `CUDA_VISIBLE_DEVICES=`:
```
Available SYCL platforms:
  - Intel(R) OpenCL, driver version OpenCL 2.1 LINUX
    - Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz, driver version 2020.9.1.0.18

  - Intel(R) OpenCL HD Graphics, driver version OpenCL 2.1 
    - Intel(R) Gen9 HD Graphics NEO, driver version 20.07.15711

  - SYCL host platform, driver version 1.2
    - SYCL host device, driver version 1.2
```

which looks like the behaviour I would expect :-)

File: sycl/plugins/cuda/pi_cuda.cpp [hunk 7]
```diff
@@ -528,43 +528,57 @@ pi_result cuda_piPlatformsGet(pi_uint32 num_entries, pi_platform *platforms,
...
-
-            int numDevices = 0;
-            err = PI_CHECK_ERROR(cuDeviceGetCount(&numDevices));
+    std::call_once(
+        initFlag,
+        [](pi_result &err) {
+          if (cuInit(0) != CUDA_SUCCESS) {
+            numPlatforms = 0;
+            return;
+          };
```
Comment (bader) [inline sycl/plugins/cuda/pi_cuda.cpp]:
```suggestion
          }
```

File: sycl/plugins/cuda/pi_cuda.cpp [hunk 8]
```diff
@@ -528,43 +528,57 @@ pi_result cuda_piPlatformsGet(pi_uint32 num_entries, pi_platform *platforms,
...
+          int numDevices = 0;
+          err = PI_CHECK_ERROR(cuDeviceGetCount(&numDevices));
+          if (numDevices == 0) {
+            numPlatforms = 0;
+            return;
+          };
```
Comment (bader) [inline sycl/plugins/cuda/pi_cuda.cpp]:
```suggestion
          }
```

File: sycl/plugins/cuda/pi_cuda.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (Ruyk) [reply sycl/plugins/cuda/pi_cuda.cpp]: I can confirm CUDA_ERROR_NO_DEVICE is reported by cuInit, despite of it not being documented. 
I think some of the other error causes are worth of throwing error, otherwise users will simply get "no cuda platform" without any other information.

File: sycl/plugins/cuda/pi_cuda.cpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (Ruyk) [reply sycl/plugins/cuda/pi_cuda.cpp]: Yes, i think that makes sense.

File: sycl/plugins/cuda/pi_cuda.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (krasznaa) [reply sycl/plugins/cuda/pi_cuda.cpp]: :confused: Do you think production code should behave that way? If I want to run an application on "some platform", I mainly want it to run. If it can't use any CUDA devices, then fine, it should still use any other device that it can, and not just die on me.

So an exception is really not what I would go for here. For whatever reason the `cuInit()` function is dying. At the most I would print an "info message" if the return value of `cuInit()` is something **really** non-expected.

[the remark this answers is not in the document]
Comment (fwyzard) [reply sycl/plugins/cuda/pi_cuda.cpp]: > I think some of the other error causes are worth of throwing error, otherwise users will simply get "no cuda platform" without any other information.

I do not know how the plugins should work in the long term.
For the moment I understand that - if they are built - both the OpenCL and the CUDA plugins will be used, without a way to select/deselect them at runtime.

Now, the OpenCL plugin seems happy in not reporting any platforms for which it doesn't find any devices.

I think the CUDA plugin should never abort (or throw an exception that causes the runtime to do so); for example because that would break also SYCL applications that do not care about the PTX/CUDA backend.

Whether to print an error or silently report no CUDA devices (and thus no CUDA platform) is less clear, but I would suggest to use the same approach as the OpenCL plugin (i.e. be silent) and let the application or the user deal with the lack of devices.

If, on the other hand, one prefers a different behaviour (e.g. warning about a CUDA installation without device, or an NVIDIA device without CUDA drivers, etc.) I think the OpenCL backend should behave in the same way with respect to OpenCL devices.
